/**********************************************************************************************************************
 * \file Driver_DfPlayer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "Driver_DfPlayer.h"

#include "IfxAsclin_Asc.h"
#include "IfxAsclin_PinMap.h"
#include "IfxCpu_Irq.h"
#include "IfxCpu.h"
#include "IfxPort.h"

#include "ActEcu_Cfg.h"

#define ASCLIN_TX_BUFFER_SIZE    64
#define ASCLIN_RX_BUFFER_SIZE    64

static IfxAsclin_Asc g_asclin2Handle;

static uint8 g_asclin2TxBuffer[ASCLIN_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_asclin2RxBuffer[ASCLIN_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

IFX_INTERRUPT(asclin2TxISR, 0, ACTECU_DFPLAYER_ISR_TX_PRIORITY);
void asclin2TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_asclin2Handle);
}

void Driver_DfPlayer_Init(void)
{
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &ACTECU_DFPLAYER_ASCLIN);

    ascConfig.baudrate.baudrate = ACTECU_DFPLAYER_BAUDRATE;

    /* TX만 사용 */
    ascConfig.interrupt.txPriority    = ACTECU_DFPLAYER_ISR_TX_PRIORITY;
    ascConfig.interrupt.rxPriority    = 0;
    ascConfig.interrupt.erPriority    = 0;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    ascConfig.txBuffer     = g_asclin2TxBuffer;
    ascConfig.txBufferSize = ASCLIN_TX_BUFFER_SIZE;
    ascConfig.rxBuffer     = g_asclin2RxBuffer;
    ascConfig.rxBufferSize = ASCLIN_RX_BUFFER_SIZE;

    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR, IfxPort_InputMode_noPullDevice,    /* CTS 미사용 */
        NULL_PTR, IfxPort_InputMode_noPullDevice,    /* RX  미사용 */
        NULL_PTR, IfxPort_OutputMode_pushPull,       /* RTS 미사용 */
        &ACTECU_DFPLAYER_TX_PIN, IfxPort_OutputMode_pushPull,
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_asclin2Handle, &ascConfig);
}

boolean DFPlayer_sendCmdOnce(uint8 cmd, uint16 param)
{
    uint8 frame[10];
    uint8 p1 = (uint8)((param >> 8) & 0xFF);
    uint8 p2 = (uint8)(param & 0xFF);
    uint16 sum;
    uint16 checksum;
    Ifx_SizeT count = 10;

    frame[0] = 0x7E;
    frame[1] = 0xFF;
    frame[2] = 0x06;
    frame[3] = cmd;
    frame[4] = 0x00;    /* feedback off */
    frame[5] = p1;
    frame[6] = p2;

    sum = (uint16)(0xFF + 0x06 + cmd + 0x00 + p1 + p2);
    checksum = (uint16)((0U - sum) & 0xFFFF);

    frame[7] = (uint8)((checksum >> 8) & 0xFF);
    frame[8] = (uint8)(checksum & 0xFF);
    frame[9] = 0xEF;

    return IfxAsclin_Asc_write(&g_asclin2Handle, frame, &count, TIME_INFINITE);
}

boolean DFPlayer_PlayFolderTrack(uint8 folder, uint8 track)
{
    uint16 param = (uint16)(((uint16)folder << 8) | (uint16)track);
    return DFPlayer_sendCmdOnce(0x0FU, param);
}

boolean DFPlayer_Stop(void)
{
    return DFPlayer_sendCmdOnce(0x16U, 0U);
}

/* UART 전송이 끝난 뒤 TX 라인을 idle high의 일반 GPIO로 강제 전환 */
void DfPlayer_releaseTxHigh(void)
{
    IfxPort_setPinModeOutput(
        ACTECU_DFPLAYER_TX_RELEASE_PORT,
        ACTECU_DFPLAYER_TX_RELEASE_PIN,
        IfxPort_OutputMode_pushPull,
        IfxPort_OutputIdx_general);

    IfxPort_setPinHigh(
        ACTECU_DFPLAYER_TX_RELEASE_PORT,
        ACTECU_DFPLAYER_TX_RELEASE_PIN);
}
