/**********************************************************************************************************************
 * \file Driver_DfPlayer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "Driver_DfPlayer.h"

#include "IfxAsclin_Asc.h"
#include "IfxAsclin_PinMap.h"
#include "IfxCpu_Irq.h"
#include "IfxCpu.h"
#include "IfxPort.h"

#include "ActEcu_Cfg.h"

#define ASCLIN_TX_BUFFER_SIZE    64
#define ASCLIN_RX_BUFFER_SIZE    64

static IfxAsclin_Asc g_state_handle;
static IfxAsclin_Asc g_event_handle;

static uint8 g_state_tx_buffer[ASCLIN_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_state_rx_buffer[ASCLIN_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

static uint8 g_event_tx_buffer[ASCLIN_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 g_event_rx_buffer[ASCLIN_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

IFX_INTERRUPT(asclin2TxISR, 0, ACTECU_DFPLAYER_STATE_ISR_TX_PRIORITY);
void asclin2TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_state_handle);
}

IFX_INTERRUPT(asclin3TxISR, 0, ACTECU_DFPLAYER_EVENT_ISR_TX_PRIORITY);
void asclin3TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_event_handle);
}

static IfxAsclin_Asc *driver_df_player_get_handle(DfPlayer_Channel channel)
{
    return (channel == DFPLAYER_CHANNEL_STATE) ? &g_state_handle : &g_event_handle;
}

static Ifx_P *driver_df_player_get_release_port(DfPlayer_Channel channel)
{
    return (channel == DFPLAYER_CHANNEL_STATE)
        ? ACTECU_DFPLAYER_STATE_TX_RELEASE_PORT
        : ACTECU_DFPLAYER_EVENT_TX_RELEASE_PORT;
}

static uint8 driver_df_player_get_release_pin(DfPlayer_Channel channel)
{
    return (channel == DFPLAYER_CHANNEL_STATE)
        ? ACTECU_DFPLAYER_STATE_TX_RELEASE_PIN
        : ACTECU_DFPLAYER_EVENT_TX_RELEASE_PIN;
}

static void driver_df_player_init_one(DfPlayer_Channel channel)
{
    IfxAsclin_Asc_Config asc_config;

    IfxAsclin_Asc *handle;
    uint8 *tx_buffer;
    uint8 *rx_buffer;

    handle    = driver_df_player_get_handle(channel);
    tx_buffer = (channel == DFPLAYER_CHANNEL_STATE) ? g_state_tx_buffer : g_event_tx_buffer;
    rx_buffer = (channel == DFPLAYER_CHANNEL_STATE) ? g_state_rx_buffer : g_event_rx_buffer;

    if (channel == DFPLAYER_CHANNEL_STATE)
    {
        IfxAsclin_Asc_initModuleConfig(&asc_config, &ACTECU_DFPLAYER_STATE_ASCLIN);
        asc_config.baudrate.baudrate     = ACTECU_DFPLAYER_STATE_BAUDRATE;
        asc_config.interrupt.txPriority  = ACTECU_DFPLAYER_STATE_ISR_TX_PRIORITY;

        {
            const IfxAsclin_Asc_Pins pins =
            {
                NULL_PTR, IfxPort_InputMode_noPullDevice,
                NULL_PTR, IfxPort_InputMode_noPullDevice,
                NULL_PTR, IfxPort_OutputMode_pushPull,
                &ACTECU_DFPLAYER_STATE_TX_PIN, IfxPort_OutputMode_pushPull,
                IfxPort_PadDriver_cmosAutomotiveSpeed1
            };

            asc_config.interrupt.rxPriority    = 0;
            asc_config.interrupt.erPriority    = 0;
            asc_config.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

            asc_config.txBuffer     = tx_buffer;
            asc_config.txBufferSize = ASCLIN_TX_BUFFER_SIZE;
            asc_config.rxBuffer     = rx_buffer;
            asc_config.rxBufferSize = ASCLIN_RX_BUFFER_SIZE;
            asc_config.pins         = &pins;

            IfxAsclin_Asc_initModule(handle, &asc_config);
        }
    }
    else
    {
        IfxAsclin_Asc_initModuleConfig(&asc_config, &ACTECU_DFPLAYER_EVENT_ASCLIN);
        asc_config.baudrate.baudrate     = ACTECU_DFPLAYER_EVENT_BAUDRATE;
        asc_config.interrupt.txPriority  = ACTECU_DFPLAYER_EVENT_ISR_TX_PRIORITY;

        {
            const IfxAsclin_Asc_Pins pins =
            {
                NULL_PTR, IfxPort_InputMode_noPullDevice,
                NULL_PTR, IfxPort_InputMode_noPullDevice,
                NULL_PTR, IfxPort_OutputMode_pushPull,
                &ACTECU_DFPLAYER_EVENT_TX_PIN, IfxPort_OutputMode_pushPull,
                IfxPort_PadDriver_cmosAutomotiveSpeed1
            };

            asc_config.interrupt.rxPriority    = 0;
            asc_config.interrupt.erPriority    = 0;
            asc_config.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

            asc_config.txBuffer     = tx_buffer;
            asc_config.txBufferSize = ASCLIN_TX_BUFFER_SIZE;
            asc_config.rxBuffer     = rx_buffer;
            asc_config.rxBufferSize = ASCLIN_RX_BUFFER_SIZE;
            asc_config.pins         = &pins;

            IfxAsclin_Asc_initModule(handle, &asc_config);
        }
    }
}

void Driver_DfPlayer_Init(void)
{
    driver_df_player_init_one(DFPLAYER_CHANNEL_STATE);
    driver_df_player_init_one(DFPLAYER_CHANNEL_EVENT);
}

boolean DFPlayer_SendCmd(DfPlayer_Channel channel, uint8 cmd, uint16 param)
{
    uint8 frame[10];
    uint8 param_high = (uint8)((param >> 8) & 0xFFu);
    uint8 param_low  = (uint8)(param & 0xFFu);
    uint16 sum;
    uint16 checksum;
    Ifx_SizeT count = 10;
    IfxAsclin_Asc *handle = driver_df_player_get_handle(channel);

    frame[0] = 0x7Eu;
    frame[1] = 0xFFu;
    frame[2] = 0x06u;
    frame[3] = cmd;
    frame[4] = 0x00u;
    frame[5] = param_high;
    frame[6] = param_low;

    sum = (uint16)(0xFFu + 0x06u + cmd + 0x00u + param_high + param_low);
    checksum = (uint16)((0u - sum) & 0xFFFFu);

    frame[7] = (uint8)((checksum >> 8) & 0xFFu);
    frame[8] = (uint8)(checksum & 0xFFu);
    frame[9] = 0xEFu;

    return IfxAsclin_Asc_write(handle, frame, &count, TIME_INFINITE);
}

boolean DFPlayer_PlayFolderTrack(DfPlayer_Channel channel, uint8 folder, uint8 track)
{
    uint16 param = (uint16)(((uint16)folder << 8) | (uint16)track);
    return DFPlayer_SendCmd(channel, 0x0Fu, param);
}

boolean DFPlayer_Stop(DfPlayer_Channel channel)
{
    return DFPlayer_SendCmd(channel, 0x16u, 0u);
}

void DfPlayer_releaseTxHigh(DfPlayer_Channel channel)
{
    IfxPort_setPinModeOutput(
        driver_df_player_get_release_port(channel),
        driver_df_player_get_release_pin(channel),
        IfxPort_OutputMode_pushPull,
        IfxPort_OutputIdx_general);

    IfxPort_setPinHigh(
        driver_df_player_get_release_port(channel),
        driver_df_player_get_release_pin(channel));
}