/**********************************************************************************************************************
 * \file Driver_Led.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 * */

#include "Driver_Led.h"
#include "ActEcu_Cfg.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"

static void Driver_Led_InitPin(const IfxPort_Pin pin)
{
    IfxPort_setPinModeOutput(
        pin.port,
        pin.pinIndex,
        IfxPort_OutputMode_pushPull,
        IfxPort_OutputIdx_general);

    IfxPort_setPinLow(pin.port, pin.pinIndex);
}

static void Driver_Led_SetPin(const IfxPort_Pin pin, boolean on)
{
    if (on == TRUE)
    {
        IfxPort_setPinHigh(pin.port, pin.pinIndex);
    }
    else
    {
        IfxPort_setPinLow(pin.port, pin.pinIndex);
    }
}

void Driver_Led_Init(void)
{
    Driver_Led_InitPin(ACTECU_LED1_PIN);

    Driver_Led_InitPin(ACTECU_LED2_1_PIN);
    Driver_Led_InitPin(ACTECU_LED2_2_PIN);
    Driver_Led_InitPin(ACTECU_LED2_3_PIN);
    Driver_Led_InitPin(ACTECU_LED2_4_PIN);

    Driver_Led_InitPin(ACTECU_LED3_NORMAL_PIN);
    Driver_Led_InitPin(ACTECU_LED3_FATAL_PIN);

    /* LED3 기본 상태 */
    Driver_Led_SetPin(ACTECU_LED3_NORMAL_PIN, TRUE);
    Driver_Led_SetPin(ACTECU_LED3_FATAL_PIN, FALSE);
}

void Driver_Led_On_1(void)
{
    IfxPort_setPinHigh(ACTECU_LED1_PIN.port, ACTECU_LED1_PIN.pinIndex);
}

void Driver_Led_Off_1(void)
{
    IfxPort_setPinLow(ACTECU_LED1_PIN.port, ACTECU_LED1_PIN.pinIndex);
}

void Driver_Led_On_2(void)
{
    IfxPort_setPinHigh(ACTECU_LED2_1_PIN.port, ACTECU_LED2_1_PIN.pinIndex);
}

void Driver_Led_Off_2(void)
{
    IfxPort_setPinLow(ACTECU_LED2_1_PIN.port, ACTECU_LED2_1_PIN.pinIndex);
}

void Driver_Led_Off_AllBrakeLamps(void)
{
    Driver_Led_SetPin(ACTECU_LED2_1_PIN, FALSE);
    Driver_Led_SetPin(ACTECU_LED2_2_PIN, FALSE);
    Driver_Led_SetPin(ACTECU_LED2_3_PIN, FALSE);
    Driver_Led_SetPin(ACTECU_LED2_4_PIN, FALSE);
}

void Driver_Led_SetBrakeLampCount(uint8 count)
{
    boolean lamp1 = FALSE;
    boolean lamp2 = FALSE;
    boolean lamp3 = FALSE;
    boolean lamp4 = FALSE;

    if (count >= 1U) { lamp1 = TRUE; }
    if (count >= 2U) { lamp2 = TRUE; }
    if (count >= 3U) { lamp3 = TRUE; }
    if (count >= 4U) { lamp4 = TRUE; }

    Driver_Led_SetPin(ACTECU_LED2_1_PIN, lamp1);
    Driver_Led_SetPin(ACTECU_LED2_2_PIN, lamp2);
    Driver_Led_SetPin(ACTECU_LED2_3_PIN, lamp3);
    Driver_Led_SetPin(ACTECU_LED2_4_PIN, lamp4);
}

void Driver_Led_Toggle_1(void)
{
    IfxPort_togglePin(ACTECU_LED1_PIN.port, ACTECU_LED1_PIN.pinIndex);
}

void Driver_Led_Toggle(void)
{
    Driver_Led_Toggle_1();
}

void Driver_Led_On_3_Normal(void)
{
    IfxPort_setPinHigh(ACTECU_LED3_NORMAL_PIN.port, ACTECU_LED3_NORMAL_PIN.pinIndex);
}

void Driver_Led_Off_3_Normal(void)
{
    IfxPort_setPinLow(ACTECU_LED3_NORMAL_PIN.port, ACTECU_LED3_NORMAL_PIN.pinIndex);
}

void Driver_Led_On_3_Fatal(void)
{
    IfxPort_setPinHigh(ACTECU_LED3_FATAL_PIN.port, ACTECU_LED3_FATAL_PIN.pinIndex);
}

void Driver_Led_Off_3_Fatal(void)
{
    IfxPort_setPinLow(ACTECU_LED3_FATAL_PIN.port, ACTECU_LED3_FATAL_PIN.pinIndex);
}
