/**********************************************************************************************************************
 * \file App_Schedular.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "App_Scheduler.h"
#include "App_Led.h"
#include "App_Buzzer.h"
#include "App_Servo.h"
#include "App_DfPlayer.h"

#include "Driver_Stm.h"
#include "Ifx_Types.h"

static App_Context g_appCtx;

void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

void App_Scheduler_SetSafeState(ActEcu_SafeState state)
{
    switch (state)
    {
    case ACTECU_SAFE_NORMAL:
    case ACTECU_SAFE_WARNING:
    case ACTECU_SAFE_CRITICAL:
    case ACTECU_SAFE_FATAL_NO_RESPONSE:
        g_appCtx.state.safeState = state;
        break;

    default:
        g_appCtx.state.safeState = ACTECU_SAFE_NORMAL;
        break;
    }
}

void App_Scheduler_SetSpeedState(uint8 speedState)
{
    g_appCtx.input.speedStateRaw = speedState;
}

void App_Scheduler_SetBrakeActive(uint8 brakeActive)
{
    g_appCtx.input.brakeActive = (brakeActive != 0U) ? 1U : 0U;
}

void App_Scheduler_SetEventState(uint8 evState)
{
    g_appCtx.input.evState = evState;
}

void App_Scheduler_SetAckButton(uint8 ackButton)
{
    g_appCtx.input.ackButton = (ackButton != 0U) ? 1U : 0U;
}

void App_Scheduler_Init(void)
{
    g_appCtx.input.safeStateRaw = 0U;
    g_appCtx.input.speedStateRaw = 0U;
    g_appCtx.input.brakeActive = 0U;
    g_appCtx.input.evState = 0U;
    g_appCtx.input.ackButton = 0U;
    g_appCtx.input.msgValid = 0U;
    g_appCtx.input.aliveCnt = 0U;
    g_appCtx.input.ackSeq = 0U;
    g_appCtx.input.ackSeqPrev = 0U;

    App_Scheduler_SetSafeState(ACTECU_SAFE_NORMAL);

    App_Led_Init(&g_appCtx);
    App_Buzzer_Init(&g_appCtx);
    App_Servo_Init(&g_appCtx);
    App_DfPlayer_Init(&g_appCtx);
}

void App_Scheduler_Run(void)
{
    if (stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if (stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if (stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }

        if (stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}

void AppTask1ms(void)
{
    /* empty */
}

void AppTask10ms(void)
{
    App_Led1_Task(&g_appCtx);
    App_Led1_Apply(&g_appCtx);

    App_Led2_Task(&g_appCtx);
    App_Led2_Apply(&g_appCtx);

    App_Buzzer_Task(&g_appCtx);
    App_Buzzer_Apply(&g_appCtx);

    App_Servo_Task(&g_appCtx);

    App_DfPlayer_Task(&g_appCtx);
    App_DfPlayer_Apply(&g_appCtx);
}

void AppTask100ms(void)
{
    /* empty */
}

void AppTask1000ms(void)
{
    /* empty */
}
