///**********************************************************************************************************************
// * \file Driver_Can.c
// * \copyright Copyright (C) Infineon Technologies AG 2019
// *
// * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
// * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
// * are agreed, use of this file is subject to following:
// *
// * Boost Software License - Version 1.0 - August 17th, 2003
// *
// * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
// * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
// * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
// * Software is furnished to do so, all subject to the following:
// *
// * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
// * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
// * derivative works of the Software, unless such copies or derivative works are solely in the form of
// * machine-executable object code generated by a source language processor.
// *
// * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
// * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// * IN THE SOFTWARE.
// *********************************************************************************************************************/
//
/**********************************************************************************************************************
 * \file Driver_Can.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *********************************************************************************************************************/

#include "Driver_Can.h"

#include "IfxPort.h"
#include "IfxMultican_Can.h"
#include "Virtual_Input.h"

volatile uint32 g_canDbgRawWord = 0u;
volatile uint8  g_canDbgByte0   = 0u;
volatile uint8  g_canDbgByte1   = 0u;
volatile uint8  g_canDbgByte2   = 0u;
volatile uint32 g_canDbgRxCount = 0u;
volatile uint32 g_canDbgStatus  = 0u;

/* =========================
 * 사용자 설정
 * ========================= */
#define RX_MSG_ID               0x201u

/* CAN 트랜시버 STB */
#define CAN_STB_PORT            (&MODULE_P20)
#define CAN_STB_PIN             6

/* =========================
 * 정적 전역 변수
 * ========================= */
static IfxMultican_Can         g_can;
static IfxMultican_Can_Node    g_canNode;
static IfxMultican_Can_MsgObj  g_rxMsgObj;
static IfxMultican_Message     g_rxMsg;

/* =========================
 * 내부 함수 선언
 * ========================= */
static void Driver_Can_InitGpio(void);
static void Driver_Can_InitModule(void);

/* =========================
 * GPIO 초기화
 * ========================= */
static void Driver_Can_InitGpio(void)
{
    /* 트랜시버 STB: LOW = normal mode */
    IfxPort_setPinMode(CAN_STB_PORT,
                       CAN_STB_PIN,
                       IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinLow(CAN_STB_PORT, CAN_STB_PIN);
}

/* =========================
 * CAN 초기화
 * - TC275 MultiCAN+
 * - Node0 사용
 * - 외부 핀 P20.7 / P20.8 사용
 * - 500 kbps
 * - ID 0x123 수신
 * - DLC 3 bytes
 * ========================= */
static void Driver_Can_InitModule(void)
{
    IfxMultican_Can_Config       canConfig;
    IfxMultican_Can_NodeConfig   nodeConfig;
    IfxMultican_Can_MsgObjConfig msgObjConfig;

    IfxMultican_Can_initModuleConfig(&canConfig, &MODULE_CAN);
    IfxMultican_Can_initModule(&g_can, &canConfig);

    IfxMultican_Can_Node_initConfig(&nodeConfig, &g_can);

    nodeConfig.nodeId       = IfxMultican_NodeId_0;
    nodeConfig.loopBackMode = FALSE;
    nodeConfig.baudrate     = 500000;

    nodeConfig.rxPin        = &IfxMultican_RXD0B_P20_7_IN;
    nodeConfig.rxPinMode    = IfxPort_InputMode_pullUp;
    nodeConfig.txPin        = &IfxMultican_TXD0_P20_8_OUT;
    nodeConfig.txPinMode    = IfxPort_OutputMode_pushPull;

    IfxMultican_Can_Node_init(&g_canNode, &nodeConfig);

    IfxMultican_Can_MsgObj_initConfig(&msgObjConfig, &g_canNode);

    msgObjConfig.msgObjId              = 1;
    msgObjConfig.messageId             = RX_MSG_ID;
    msgObjConfig.frame                 = IfxMultican_Frame_receive;
    msgObjConfig.control.extendedFrame = FALSE;
    msgObjConfig.control.messageLen    = IfxMultican_DataLengthCode_3;
    msgObjConfig.rxInterrupt.enabled   = FALSE;

    IfxMultican_Can_MsgObj_init(&g_rxMsgObj, &msgObjConfig);

    IfxMultican_Message_init(&g_rxMsg,
                             RX_MSG_ID,
                             0u,
                             0u,
                             IfxMultican_DataLengthCode_3);
}

void Driver_Can_Init(void)
{
    Driver_Can_InitGpio();
    Driver_Can_InitModule();
}

void Driver_Can_Task(void)
{
    IfxMultican_Status status;
    uint32 rawWord;
    uint8 byte0;
    uint8 byte1;
    uint8 byte2;

    status = IfxMultican_Can_MsgObj_readMessage(&g_rxMsgObj, &g_rxMsg);
    g_canDbgStatus = (uint32)status;

    if ((status & IfxMultican_Status_newData) == 0u)
    {
        return;
    }

    /* CAN RX payload 3 bytes -> 기존 Virtual_Input 해석기로 전달 */
    rawWord = g_rxMsg.data[0];

    byte0 = (uint8)( rawWord        & 0xFFu);
    byte1 = (uint8)((rawWord >> 8)  & 0xFFu);
    byte2 = (uint8)((rawWord >> 16) & 0xFFu);

    g_canDbgRawWord = rawWord;
    g_canDbgByte0   = byte0;
    g_canDbgByte1   = byte1;
    g_canDbgByte2   = byte2;
    g_canDbgRxCount++;

    Virtual_Input_InjectorWriteFrame(byte0, byte1, byte2);
}
