///**********************************************************************************************************************
// * \file Driver_Can.c
// * \copyright Copyright (C) Infineon Technologies AG 2019
// *
// * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
// * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
// * are agreed, use of this file is subject to following:
// *
// * Boost Software License - Version 1.0 - August 17th, 2003
// *
// * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
// * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
// * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
// * Software is furnished to do so, all subject to the following:
// *
// * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
// * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
// * derivative works of the Software, unless such copies or derivative works are solely in the form of
// * machine-executable object code generated by a source language processor.
// *
// * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
// * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// * IN THE SOFTWARE.
// *********************************************************************************************************************/
//
/**********************************************************************************************************************
 * \file Driver_Can.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *********************************************************************************************************************/

#include "Driver_Can.h"

#include "IfxPort.h"
#include "IfxMultican_Can.h"
#include "Virtual_Input.h"

volatile uint32 g_can_dbg_raw_word = 0u;
volatile uint8  g_can_dbg_byte0    = 0u;
volatile uint8  g_can_dbg_byte1    = 0u;
volatile uint8  g_can_dbg_byte2    = 0u;
volatile uint32 g_can_dbg_rx_count = 0u;
volatile uint32 g_can_dbg_status   = 0u;

#define RX_MSG_ID               0x201u

#define CAN_STB_PORT            (&MODULE_P20)
#define CAN_STB_PIN             6

static IfxMultican_Can        g_can;
static IfxMultican_Can_Node   g_can_node;
static IfxMultican_Can_MsgObj g_rx_msg_obj;
static IfxMultican_Message    g_rx_msg;

static void driver_can_init_gpio(void);
static void driver_can_init_module(void);

static void driver_can_init_gpio(void)
{
    /* 트랜시버 STB: LOW = normal mode */
    IfxPort_setPinMode(CAN_STB_PORT,
                       CAN_STB_PIN,
                       IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinLow(CAN_STB_PORT, CAN_STB_PIN);
}

/* =========================
 * CAN 초기화
 * - TC275 MultiCAN+
 * - Node0 사용
 * - 외부 핀 P20.7 / P20.8 사용
 * - 500 kbps
 * - ID 0x201 수신
 * - DLC 3 bytes
 * ========================= */
static void driver_can_init_module(void)
{
    IfxMultican_Can_Config       can_config;
    IfxMultican_Can_NodeConfig   node_config;
    IfxMultican_Can_MsgObjConfig msg_obj_config;

    IfxMultican_Can_initModuleConfig(&can_config, &MODULE_CAN);
    IfxMultican_Can_initModule(&g_can, &can_config);

    IfxMultican_Can_Node_initConfig(&node_config, &g_can);

    node_config.nodeId       = IfxMultican_NodeId_0;
    node_config.loopBackMode = FALSE;
    node_config.baudrate     = 500000;

    node_config.rxPin        = &IfxMultican_RXD0B_P20_7_IN;
    node_config.rxPinMode    = IfxPort_InputMode_pullUp;
    node_config.txPin        = &IfxMultican_TXD0_P20_8_OUT;
    node_config.txPinMode    = IfxPort_OutputMode_pushPull;

    IfxMultican_Can_Node_init(&g_can_node, &node_config);

    IfxMultican_Can_MsgObj_initConfig(&msg_obj_config, &g_can_node);

    msg_obj_config.msgObjId              = 1;
    msg_obj_config.messageId             = RX_MSG_ID;
    msg_obj_config.frame                 = IfxMultican_Frame_receive;
    msg_obj_config.control.extendedFrame = FALSE;
    msg_obj_config.control.messageLen    = IfxMultican_DataLengthCode_3;
    msg_obj_config.rxInterrupt.enabled   = FALSE;

    IfxMultican_Can_MsgObj_init(&g_rx_msg_obj, &msg_obj_config);

    IfxMultican_Message_init(&g_rx_msg,
                             RX_MSG_ID,
                             0u,
                             0u,
                             IfxMultican_DataLengthCode_3);
}

void Driver_Can_Init(void)
{
    driver_can_init_gpio();
    driver_can_init_module();
}

void Driver_Can_Task(void)
{
    IfxMultican_Status status;
    uint32 raw_word;
    uint8  byte0;
    uint8  byte1;
    uint8  byte2;

    status = IfxMultican_Can_MsgObj_readMessage(&g_rx_msg_obj, &g_rx_msg);
    g_can_dbg_status = (uint32)status;

    if ((status & IfxMultican_Status_newData) == 0u)
    {
        return;
    }

    raw_word = g_rx_msg.data[0];

    byte0 = (uint8)( raw_word        & 0xFFu);
    byte1 = (uint8)((raw_word >> 8)  & 0xFFu);
    byte2 = (uint8)((raw_word >> 16) & 0xFFu);

    g_can_dbg_raw_word = raw_word;
    g_can_dbg_byte0    = byte0;
    g_can_dbg_byte1    = byte1;
    g_can_dbg_byte2    = byte2;
    g_can_dbg_rx_count++;

    Virtual_Input_InjectorWriteFrame(byte0, byte1, byte2);
}