/**********************************************************************************************************************
 * \file App_Led.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "App_Led.h"
#include "ActEcu_Params.h"
#include "Driver_Led.h"

void App_Led_Init(App_Context *ctx)
{
    ctx->led1_ctrl.led1_on = FALSE;
    ctx->led1_ctrl.led1_blink_elapsed_ms = 0U;

    ctx->led2_ctrl.brake_lamp_count = 0U;

    ctx->led3_ctrl.normal_lamp_on = TRUE;
    ctx->led3_ctrl.fatal_lamp_on  = FALSE;

    Driver_Led_Off_1();
    Driver_Led_Off_AllBrakeLamps();

    Driver_Led_On_3_Normal();
    Driver_Led_Off_3_Fatal();
}

void App_Led1_Task(App_Context *ctx)
{
    uint16 on_ms = 0U;
    uint16 off_ms = 0U;

    switch (ctx->state.safe_state)
    {
    case ACTECU_SAFE_NORMAL:
    case ACTECU_SAFE_WARNING:
        ctx->led1_ctrl.led1_on = FALSE;
        ctx->led1_ctrl.led1_blink_elapsed_ms = 0U;
        return;

    case ACTECU_SAFE_CRITICAL:
        on_ms  = P_LED1_CRITICAL_BLINK_ON_MS;
        off_ms = P_LED1_CRITICAL_BLINK_OFF_MS;
        break;

    case ACTECU_SAFE_FATAL_NO_RESPONSE:
        on_ms  = P_LED1_FATAL_BLINK_ON_MS;
        off_ms = P_LED1_FATAL_BLINK_OFF_MS;
        break;

    default:
        ctx->led1_ctrl.led1_on = FALSE;
        ctx->led1_ctrl.led1_blink_elapsed_ms = 0U;
        return;
    }

    ctx->led1_ctrl.led1_blink_elapsed_ms += ACTECU_LED1_TASK_PERIOD_MS;

    if (ctx->led1_ctrl.led1_on == TRUE)
    {
        if (ctx->led1_ctrl.led1_blink_elapsed_ms >= on_ms)
        {
            ctx->led1_ctrl.led1_on = FALSE;
            ctx->led1_ctrl.led1_blink_elapsed_ms = 0U;
        }
    }
    else
    {
        if (ctx->led1_ctrl.led1_blink_elapsed_ms >= off_ms)
        {
            ctx->led1_ctrl.led1_on = TRUE;
            ctx->led1_ctrl.led1_blink_elapsed_ms = 0U;
        }
    }
}

void App_Led1_Apply(const App_Context *ctx)
{
    if (ctx->led1_ctrl.led1_on == TRUE)
    {
        Driver_Led_On_1();
    }
    else
    {
        Driver_Led_Off_1();
    }
}

void App_Led2_Task(App_Context *ctx)
{
    uint8 lamp_count = 0U;

    switch (ctx->state.safe_state)
    {
    case ACTECU_SAFE_FATAL_NO_RESPONSE:
        lamp_count = 4U;
        break;

    case ACTECU_SAFE_CRITICAL:
        lamp_count = 2U;
        break;

    case ACTECU_SAFE_WARNING:
        lamp_count = 1U;
        break;

    case ACTECU_SAFE_NORMAL:
    default:
        if (ctx->input.brake_active != 0U)
        {
            lamp_count = 1U;
        }
        else
        {
            lamp_count = 0U;
        }
        break;
    }

    ctx->led2_ctrl.brake_lamp_count = lamp_count;
}

void App_Led2_Apply(const App_Context *ctx)
{
    Driver_Led_SetBrakeLampCount(ctx->led2_ctrl.brake_lamp_count);
}

void App_Led3_Task(App_Context *ctx)
{
    if (ctx->state.safe_state == ACTECU_SAFE_FATAL_NO_RESPONSE)
    {
        ctx->led3_ctrl.normal_lamp_on = FALSE;
        ctx->led3_ctrl.fatal_lamp_on  = TRUE;
    }
    else
    {
        ctx->led3_ctrl.normal_lamp_on = TRUE;
        ctx->led3_ctrl.fatal_lamp_on  = FALSE;
    }
}

void App_Led3_Apply(const App_Context *ctx)
{
    if (ctx->led3_ctrl.normal_lamp_on == TRUE)
    {
        Driver_Led_On_3_Normal();
    }
    else
    {
        Driver_Led_Off_3_Normal();
    }

    if (ctx->led3_ctrl.fatal_lamp_on == TRUE)
    {
        Driver_Led_On_3_Fatal();
    }
    else
    {
        Driver_Led_Off_3_Fatal();
    }
}