/**********************************************************************************************************************
 * \file Driver_Buzzer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Driver_Buzzer.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"
#include "IfxGtm.h"
#include "ActEcu_Cfg.h"
#include "ActEcu_Params.h"

static IfxGtm_Tom_Pwm_Config g_buzzer_tom_config;
static IfxGtm_Tom_Pwm_Driver g_buzzer_tom_driver;

static void make_sound(unsigned int note_idx);

void Driver_Buzzer_Init(void)
{
    IfxGtm_enable(&MODULE_GTM);
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);

    IfxGtm_Tom_Pwm_initConfig(&g_buzzer_tom_config, &MODULE_GTM);

    g_buzzer_tom_config.tom                      = ACTECU_BUZZER_PIN.tom;
    g_buzzer_tom_config.tomChannel               = ACTECU_BUZZER_PIN.channel;
    g_buzzer_tom_config.pin.outputPin            = &ACTECU_BUZZER_PIN;
    g_buzzer_tom_config.clock                    = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk1;
    g_buzzer_tom_config.period                   = 1000U;
    g_buzzer_tom_config.dutyCycle                = 0U;
    g_buzzer_tom_config.synchronousUpdateEnabled = TRUE;

    IfxGtm_Tom_Pwm_init(&g_buzzer_tom_driver, &g_buzzer_tom_config);
    IfxGtm_Tom_Pwm_start(&g_buzzer_tom_driver, TRUE);

    Driver_Buzzer_Off();
}

static void make_sound(unsigned int note_idx)
{
    uint16 u_period = 0U;
    static const float f_buzz[15] =
    {
        261.63f,
        277.18f,
        293.66f,
        311.13f,
        329.63f,
        349.23f,
        369.99f,
        392.00f,
        415.30f,
        440.00f,
        466.16f,
        493.88f,
        523.25f,   
        554.37f,
        0.0f       
    };

    if (note_idx >= 15U)
    {
        note_idx = 14U;
    }

    if (note_idx == 14U)
    {
        g_buzzer_tom_config.dutyCycle = 0U;
        IfxGtm_Tom_Pwm_init(&g_buzzer_tom_driver, &g_buzzer_tom_config);
        return;
    }

    u_period = (uint16)(ACTECU_BUZZER_TOM_CLK_HZ / f_buzz[note_idx]);

    g_buzzer_tom_config.period    = u_period;
    g_buzzer_tom_config.dutyCycle = (uint16)(u_period / 2U);

    IfxGtm_Tom_Pwm_init(&g_buzzer_tom_driver, &g_buzzer_tom_config);
}

void Driver_Buzzer_SetNote(unsigned int note_idx)
{
    make_sound(note_idx);
}

void Driver_Buzzer_On(void)
{
    make_sound(P_BUZZER_DEFAULT_NOTE_IDX);
}

void Driver_Buzzer_Off(void)
{
    make_sound(P_BUZZER_OFF_NOTE_IDX);
}