/**********************************************************************************************************************
 * \file Driver_Servo.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Driver_Servo.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"
#include "IfxGtm.h"
#include "IfxStm.h"
#include "Bsp.h"
#include "ActEcu_Cfg.h"

static IfxGtm_Tom_Pwm_Config g_tomConfigServo1;
static IfxGtm_Tom_Pwm_Driver g_tomDriverServo1;

static IfxGtm_Tom_Pwm_Config g_tomConfigServo2;
static IfxGtm_Tom_Pwm_Driver g_tomDriverServo2;

static IfxGtm_Tom_Pwm_Config g_tomConfigServo3;
static IfxGtm_Tom_Pwm_Driver g_tomDriverServo3;

static uint32 servoPulseUsToTicks(uint32 pulseUs)
{
    return (uint32)(((uint64)ACTECU_SERVO_TOM_CLK_HZ * (uint64)pulseUs) / 1000000ULL);
}

static uint32 Driver_Servo_ClampPulseUs(uint32 pulseUs)
{
    if (pulseUs < ACTECU_SERVO_MIN_US)
    {
        pulseUs = ACTECU_SERVO_MIN_US;
    }
    else if (pulseUs > ACTECU_SERVO_MAX_US)
    {
        pulseUs = ACTECU_SERVO_MAX_US;
    }

    return pulseUs;
}

static void Driver_Servo_InitChannel(IfxGtm_Tom_Pwm_Config *config,
                                     IfxGtm_Tom_Pwm_Driver *driver,
                                     const IfxGtm_Tom_ToutMap *pinMap)
{
    IfxGtm_Tom_Pwm_initConfig(config, &MODULE_GTM);

    config->clock                    = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk1;
    config->tom                      = pinMap->tom;
    config->tomChannel               = pinMap->channel;
    config->pin.outputPin            = pinMap;
    config->period                   = ACTECU_SERVO_PERIOD_TICKS;
    config->dutyCycle                = servoPulseUsToTicks(ACTECU_SERVO_CENTER_US);
    config->synchronousUpdateEnabled = TRUE;

    IfxGtm_Tom_Pwm_init(driver, config);
    IfxGtm_Tom_Pwm_start(driver, TRUE);
}

static void Driver_Servo_UpdateChannel(IfxGtm_Tom_Pwm_Config *config,
                                       IfxGtm_Tom_Pwm_Driver *driver,
                                       uint32 pulseUs)
{
    config->dutyCycle = servoPulseUsToTicks(pulseUs);
    IfxGtm_Tom_Pwm_init(driver, config);
}

void Driver_Servo_Init(void)
{
    IfxGtm_enable(&MODULE_GTM);
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);

    Driver_Servo_InitChannel(&g_tomConfigServo1, &g_tomDriverServo1, &ACTECU_SERVO1_PIN);
    Driver_Servo_InitChannel(&g_tomConfigServo2, &g_tomDriverServo2, &ACTECU_SERVO2_PIN);
    Driver_Servo_InitChannel(&g_tomConfigServo3, &g_tomDriverServo3, &ACTECU_SERVO3_PIN);
}

void setServo1PulseUs(uint32 pulseUs)
{
    pulseUs = Driver_Servo_ClampPulseUs(pulseUs);
    Driver_Servo_UpdateChannel(&g_tomConfigServo1, &g_tomDriverServo1, pulseUs);
}

void setServo2PulseUs(uint32 pulseUs)
{
    pulseUs = Driver_Servo_ClampPulseUs(pulseUs);
    Driver_Servo_UpdateChannel(&g_tomConfigServo2, &g_tomDriverServo2, pulseUs);
}

void setServo3PulseUs(uint32 pulseUs)
{
    pulseUs = Driver_Servo_ClampPulseUs(pulseUs);
    Driver_Servo_UpdateChannel(&g_tomConfigServo3, &g_tomDriverServo3, pulseUs);
}

void setServoAllPulseUs(uint32 pulseUs)
{
    pulseUs = Driver_Servo_ClampPulseUs(pulseUs);
    Driver_Servo_UpdateChannel(&g_tomConfigServo1, &g_tomDriverServo1, pulseUs);
    Driver_Servo_UpdateChannel(&g_tomConfigServo2, &g_tomDriverServo2, pulseUs);
    Driver_Servo_UpdateChannel(&g_tomConfigServo3, &g_tomDriverServo3, pulseUs);
}

/* 기존 코드 호환용 */
void setServoPulseUs(uint32 pulseUs)
{
    setServoAllPulseUs(pulseUs);
}

void servoRampUs(uint32 startUs, uint32 endUs, uint32 totalMs, uint32 stepMs)
{
    uint32 i;
    uint32 stepCount;
    sint32 diff;

    if (stepMs == 0U)
    {
        stepMs = 20U;
    }

    stepCount = totalMs / stepMs;
    if (stepCount == 0U)
    {
        stepCount = 1U;
    }

    diff = (sint32)endUs - (sint32)startUs;

    for (i = 0U; i <= stepCount; i++)
    {
        uint32 pulseUs;

        pulseUs = (uint32)((sint32)startUs + ((diff * (sint32)i) / (sint32)stepCount));
        setServoAllPulseUs(pulseUs);

        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, stepMs));
    }

    setServoAllPulseUs(endUs);
}
