/**********************************************************************************************************************
 * \file Driver_Servo.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Driver_Servo.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"
#include "IfxGtm.h"
#include "Bsp.h"
#include "ActEcu_Cfg.h"

IfxGtm_Tom_Pwm_Config g_tomConfigServo;
IfxGtm_Tom_Pwm_Driver g_tomDriverServo;

static uint32 servoPulseUsToTicks(uint32 pulseUs)
{
    return (uint32)(((uint64)ACTECU_SERVO_TOM_CLK_HZ * (uint64)pulseUs) / 1000000ULL);
}

void Driver_Servo_Init(void)
{
    IfxGtm_enable(&MODULE_GTM);
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);

    /* 반드시 initConfig 먼저 */
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfigServo, &MODULE_GTM);

    /* 그 다음 clock, pin, period 설정 */
    g_tomConfigServo.clock = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk1;
    g_tomConfigServo.tom = ACTECU_SERVO_PIN.tom;
    g_tomConfigServo.tomChannel = ACTECU_SERVO_PIN.channel;
    g_tomConfigServo.pin.outputPin = &ACTECU_SERVO_PIN;

    g_tomConfigServo.period = ACTECU_SERVO_PERIOD_TICKS;                  /* 20ms */
    g_tomConfigServo.dutyCycle = servoPulseUsToTicks(ACTECU_SERVO_MIN_US);/* 1000us 시작 */
    g_tomConfigServo.synchronousUpdateEnabled = TRUE;

    IfxGtm_Tom_Pwm_init(&g_tomDriverServo, &g_tomConfigServo);
    IfxGtm_Tom_Pwm_start(&g_tomDriverServo, TRUE);
}

void setServoPulseUs(uint32 pulseUs)
{
    if (pulseUs < ACTECU_SERVO_MIN_US)
    {
        pulseUs = ACTECU_SERVO_MIN_US;
    }
    else if (pulseUs > ACTECU_SERVO_MAX_US)
    {
        pulseUs = ACTECU_SERVO_MAX_US;
    }

    g_tomConfigServo.dutyCycle = servoPulseUsToTicks(pulseUs);
    IfxGtm_Tom_Pwm_init(&g_tomDriverServo, &g_tomConfigServo);
}

void servoRampUs(uint32 startUs, uint32 endUs, uint32 totalMs, uint32 stepMs)
{
    uint32 i;
    uint32 stepCount;
    sint32 diff;

    if (stepMs == 0U)
    {
        stepMs = 20U;
    }

    stepCount = totalMs / stepMs;
    if (stepCount == 0U)
    {
        stepCount = 1U;
    }

    diff = (sint32)endUs - (sint32)startUs;

    for (i = 0U; i <= stepCount; i++)
    {
        uint32 pulseUs;

        pulseUs = (uint32)((sint32)startUs + ((diff * (sint32)i) / (sint32)stepCount));
        setServoPulseUs(pulseUs);

        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, stepMs));
    }

    /* 마지막 값을 정확히 endUs로 한 번 더 고정 */
    setServoPulseUs(endUs);
}
