/**********************************************************************************************************************
 * \file App_DfPlayer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "App_DfPlayer.h"

#include "ActEcu_Params.h"
#include "Driver_DfPlayer.h"

static App_AudioState App_DfPlayer_MapPersistentState(const App_Context *ctx)
{
    if (ctx->state.safeState == ACTECU_SAFE_FATAL_NO_RESPONSE)
    {
        return APP_AUDIO_FATAL;
    }

    if ((ctx->state.safeState == ACTECU_SAFE_CRITICAL) ||
        (ctx->input.evState == (uint8)ACTECU_EVENT_FAULT))
    {
        return APP_AUDIO_FAULT;
    }

    switch ((ActEcu_SpeedState)ctx->input.speedStateRaw)
    {
    case ACTECU_SPEED_LOW:
        return APP_AUDIO_LOW_SPEED;

    case ACTECU_SPEED_MID:
        return APP_AUDIO_MID_SPEED;

    case ACTECU_SPEED_HIGH:
        return APP_AUDIO_HIGH_SPEED;

    case ACTECU_SPEED_STOP:
    default:
        return APP_AUDIO_STARTUP;
    }
}

static App_AudioState App_DfPlayer_MapEventState(uint8 evState)
{
    switch ((ActEcu_EventState)evState)
    {
    case ACTECU_EVENT_RAPID_BRAKE:
        return APP_AUDIO_RAPID_BRAKE;

    case ACTECU_EVENT_RAPID_ACCEL:
        return APP_AUDIO_RAPID_ACCEL;

    case ACTECU_EVENT_STEER_LEVEL1:
        return APP_AUDIO_STEER_LEVEL1;

    case ACTECU_EVENT_STEER_LEVEL2:
        return APP_AUDIO_STEER_LEVEL2;

    default:
        return APP_AUDIO_NONE;
    }
}

static uint8 App_DfPlayer_GetTrackNo(App_AudioState state)
{
    switch (state)
    {
    case APP_AUDIO_STARTUP:
        return P_DFPLAYER_TRACK_STARTUP;

    case APP_AUDIO_LOW_SPEED:
        return P_DFPLAYER_TRACK_LOW_SPEED;

    case APP_AUDIO_MID_SPEED:
        return P_DFPLAYER_TRACK_MID_SPEED;

    case APP_AUDIO_HIGH_SPEED:
        return P_DFPLAYER_TRACK_HIGH_SPEED;

    case APP_AUDIO_RAPID_BRAKE:
        return P_DFPLAYER_TRACK_RAPID_BRAKE;

    case APP_AUDIO_RAPID_ACCEL:
        return P_DFPLAYER_TRACK_RAPID_ACCEL;

    case APP_AUDIO_STEER_LEVEL1:
        return P_DFPLAYER_TRACK_STEER_LEVEL1;

    case APP_AUDIO_STEER_LEVEL2:
        return P_DFPLAYER_TRACK_STEER_LEVEL2;

    case APP_AUDIO_FAULT:
        return P_DFPLAYER_TRACK_FAULT;

    case APP_AUDIO_FATAL:
        return P_DFPLAYER_TRACK_FATAL;

    case APP_AUDIO_NONE:
    default:
        return 0U;
    }
}

void App_DfPlayer_Init(App_Context *ctx)
{
    ctx->dfPlayerCtrl.currentState = APP_AUDIO_NONE;
    ctx->dfPlayerCtrl.prevAppliedState = APP_AUDIO_NONE;
    ctx->dfPlayerCtrl.eventState = APP_AUDIO_NONE;
    ctx->dfPlayerCtrl.eventActive = FALSE;
    ctx->dfPlayerCtrl.eventElapsedMs = 0U;
    ctx->dfPlayerCtrl.prevEvState = (uint8)ACTECU_EVENT_NONE;
    ctx->dfPlayerCtrl.prevAckButton = 0U;
}

void App_DfPlayer_Task(App_Context *ctx)
{
    App_AudioState persistentState;
    App_AudioState newEventState = APP_AUDIO_NONE;
    uint8 evState = ctx->input.evState;
    uint8 ackButton = ctx->input.ackButton;

    if ((evState != ctx->dfPlayerCtrl.prevEvState) &&
        (evState != (uint8)ACTECU_EVENT_NONE))
    {
        newEventState = App_DfPlayer_MapEventState(evState);
    }

    ctx->dfPlayerCtrl.prevEvState = evState;

    if (ackButton != 0U)
    {
        ctx->dfPlayerCtrl.eventActive = FALSE;
        ctx->dfPlayerCtrl.eventState = APP_AUDIO_NONE;
        ctx->dfPlayerCtrl.eventElapsedMs = 0U;
        ctx->dfPlayerCtrl.currentState = APP_AUDIO_NONE;
        ctx->dfPlayerCtrl.prevAckButton = ackButton;
        return;
    }

    ctx->dfPlayerCtrl.prevAckButton = ackButton;

    persistentState = App_DfPlayer_MapPersistentState(ctx);

    if ((persistentState == APP_AUDIO_FAULT) ||
        (persistentState == APP_AUDIO_FATAL))
    {
        ctx->dfPlayerCtrl.eventActive = FALSE;
        ctx->dfPlayerCtrl.eventState = APP_AUDIO_NONE;
        ctx->dfPlayerCtrl.eventElapsedMs = 0U;
        ctx->dfPlayerCtrl.currentState = persistentState;
        return;
    }

    if (newEventState != APP_AUDIO_NONE)
    {
        ctx->dfPlayerCtrl.eventActive = TRUE;
        ctx->dfPlayerCtrl.eventState = newEventState;
        ctx->dfPlayerCtrl.eventElapsedMs = 0U;
        ctx->dfPlayerCtrl.currentState = newEventState;
        return;
    }

    if (ctx->dfPlayerCtrl.eventActive == TRUE)
    {
        if (ctx->dfPlayerCtrl.eventElapsedMs < P_DFPLAYER_EVENT_HOLD_MS)
        {
            ctx->dfPlayerCtrl.eventElapsedMs += ACTECU_DFPLAYER_TASK_PERIOD_MS;
            ctx->dfPlayerCtrl.currentState = ctx->dfPlayerCtrl.eventState;
            return;
        }

        ctx->dfPlayerCtrl.eventActive = FALSE;
        ctx->dfPlayerCtrl.eventState = APP_AUDIO_NONE;
        ctx->dfPlayerCtrl.eventElapsedMs = 0U;
    }

    ctx->dfPlayerCtrl.currentState = persistentState;
}

void App_DfPlayer_Apply(App_Context *ctx)
{
    uint8 trackNo;

    if (ctx->dfPlayerCtrl.currentState == ctx->dfPlayerCtrl.prevAppliedState)
    {
        return;
    }

    if (ctx->dfPlayerCtrl.currentState == APP_AUDIO_NONE)
    {
        (void)DFPlayer_Stop();
        ctx->dfPlayerCtrl.prevAppliedState = APP_AUDIO_NONE;
        return;
    }

    trackNo = App_DfPlayer_GetTrackNo(ctx->dfPlayerCtrl.currentState);

    if (trackNo != 0U)
    {
        (void)DFPlayer_PlayFolderTrack(P_DFPLAYER_FOLDER_NO, trackNo);
        ctx->dfPlayerCtrl.prevAppliedState = ctx->dfPlayerCtrl.currentState;
    }
}
