/**********************************************************************************************************************
 * \file App_DfPlayer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "App_DfPlayer.h"

#include "ActEcu_Params.h"
#include "Driver_DfPlayer.h"

static App_AudioState App_DfPlayer_MapStateAudio(const App_Context *ctx)
{
    if (ctx->state.safeState == ACTECU_SAFE_FATAL_NO_RESPONSE)
    {
        return APP_AUDIO_FATAL;
    }

    if ((ctx->state.safeState == ACTECU_SAFE_CRITICAL) ||
        (ctx->input.evState == (uint8)ACTECU_EVENT_FAULT))
    {
        return APP_AUDIO_FAULT;
    }

    switch ((ActEcu_SpeedState)ctx->input.speedStateRaw)
    {
    case ACTECU_SPEED_LOW:
        return APP_AUDIO_LOW_SPEED;

    case ACTECU_SPEED_MID:
        return APP_AUDIO_MID_SPEED;

    case ACTECU_SPEED_HIGH:
        return APP_AUDIO_HIGH_SPEED;

    case ACTECU_SPEED_STOP:
    default:
        return APP_AUDIO_NONE;
    }
}

static App_AudioState App_DfPlayer_MapEventAudio(uint8 evState)
{
    switch ((ActEcu_EventState)evState)
    {
    case ACTECU_EVENT_RAPID_BRAKE:
        return APP_AUDIO_RAPID_BRAKE;

    case ACTECU_EVENT_RAPID_ACCEL:
        return APP_AUDIO_RAPID_ACCEL;

    case ACTECU_EVENT_STEER_LEVEL1:
        return APP_AUDIO_STEER_LEVEL1;

    case ACTECU_EVENT_STEER_LEVEL2:
        return APP_AUDIO_STEER_LEVEL2;

    default:
        return APP_AUDIO_NONE;
    }
}

static uint8 App_DfPlayer_GetStateTrackNo(App_AudioState state)
{
    switch (state)
    {
    case APP_AUDIO_LOW_SPEED:
        return P_DFPLAYER_STATE_TRACK_LOW_SPEED;

    case APP_AUDIO_MID_SPEED:
        return P_DFPLAYER_STATE_TRACK_MID_SPEED;

    case APP_AUDIO_HIGH_SPEED:
        return P_DFPLAYER_STATE_TRACK_HIGH_SPEED;

    case APP_AUDIO_FAULT:
        return P_DFPLAYER_STATE_TRACK_FAULT;

    case APP_AUDIO_FATAL:
        return P_DFPLAYER_STATE_TRACK_FATAL;

    default:
        return 0U;
    }
}

static uint8 App_DfPlayer_GetEventTrackNo(App_AudioState state)
{
    switch (state)
    {
    case APP_AUDIO_STARTUP:
        return P_DFPLAYER_EVENT_TRACK_STARTUP;

    case APP_AUDIO_RAPID_BRAKE:
        return P_DFPLAYER_EVENT_TRACK_RAPID_BRAKE;

    case APP_AUDIO_RAPID_ACCEL:
        return P_DFPLAYER_EVENT_TRACK_RAPID_ACCEL;

    case APP_AUDIO_STEER_LEVEL1:
        return P_DFPLAYER_EVENT_TRACK_STEER_LEVEL1;

    case APP_AUDIO_STEER_LEVEL2:
        return P_DFPLAYER_EVENT_TRACK_STEER_LEVEL2;

    default:
        return 0U;
    }
}

void App_DfPlayer_Init(App_Context *ctx)
{
    ctx->dfPlayerStateCtrl.currentState = APP_AUDIO_NONE;
    ctx->dfPlayerStateCtrl.prevAppliedState = APP_AUDIO_NONE;
    ctx->dfPlayerStateCtrl.repeatElapsedMs = 0U;

    ctx->dfPlayerEventCtrl.pendingState = APP_AUDIO_STARTUP;
    ctx->dfPlayerEventCtrl.prevEvState = (uint8)ACTECU_EVENT_NONE;
    ctx->dfPlayerEventCtrl.playReq = TRUE;
}

void App_DfPlayer_Task(App_Context *ctx)
{
    App_AudioState stateAudio;
    App_AudioState newEventAudio;
    uint8 evState = ctx->input.evState;

    stateAudio = App_DfPlayer_MapStateAudio(ctx);

    if (ctx->dfPlayerStateCtrl.currentState != stateAudio)
    {
        ctx->dfPlayerStateCtrl.currentState = stateAudio;
        ctx->dfPlayerStateCtrl.repeatElapsedMs = 0U;
    }
    else
    {
        if (stateAudio != APP_AUDIO_NONE)
        {
            if (ctx->dfPlayerStateCtrl.repeatElapsedMs < P_DFPLAYER_STATE_REPEAT_MS)
            {
                ctx->dfPlayerStateCtrl.repeatElapsedMs += ACTECU_DFPLAYER_TASK_PERIOD_MS;
            }
        }
        else
        {
            ctx->dfPlayerStateCtrl.repeatElapsedMs = 0U;
        }
    }

    if ((evState != ctx->dfPlayerEventCtrl.prevEvState) &&
        (evState != (uint8)ACTECU_EVENT_NONE))
    {
        newEventAudio = App_DfPlayer_MapEventAudio(evState);

        if (newEventAudio != APP_AUDIO_NONE)
        {
            ctx->dfPlayerEventCtrl.pendingState = newEventAudio;
            ctx->dfPlayerEventCtrl.playReq = TRUE;
        }
    }

    ctx->dfPlayerEventCtrl.prevEvState = evState;
}

void App_DfPlayer_Apply(App_Context *ctx)
{
    uint8 trackNo;

    /* -------------------------------------------------------------- */
    /* 상태 스피커 : 같은 상태면 주기적으로 다시 Play                  */
    /* -------------------------------------------------------------- */
    if (ctx->dfPlayerStateCtrl.currentState == APP_AUDIO_NONE)
    {
        if (ctx->dfPlayerStateCtrl.prevAppliedState != APP_AUDIO_NONE)
        {
            (void)DFPlayer_Stop(DFPLAYER_CHANNEL_STATE);
            ctx->dfPlayerStateCtrl.prevAppliedState = APP_AUDIO_NONE;
            ctx->dfPlayerStateCtrl.repeatElapsedMs = 0U;
        }
    }
    else
    {
        if ((ctx->dfPlayerStateCtrl.currentState != ctx->dfPlayerStateCtrl.prevAppliedState) ||
            (ctx->dfPlayerStateCtrl.repeatElapsedMs >= P_DFPLAYER_STATE_REPEAT_MS))
        {
            trackNo = App_DfPlayer_GetStateTrackNo(ctx->dfPlayerStateCtrl.currentState);

            if (trackNo != 0U)
            {
                (void)DFPlayer_PlayFolderTrack(
                    DFPLAYER_CHANNEL_STATE,
                    P_DFPLAYER_STATE_FOLDER_NO,
                    trackNo);

                ctx->dfPlayerStateCtrl.prevAppliedState = ctx->dfPlayerStateCtrl.currentState;
                ctx->dfPlayerStateCtrl.repeatElapsedMs = 0U;
            }
        }
    }

    /* -------------------------------------------------------------- */
    /* 이벤트 스피커 : 변화가 생겼을 때만 1회 재생                     */
    /* -------------------------------------------------------------- */
    if ((ctx->dfPlayerEventCtrl.playReq == TRUE) &&
        (ctx->dfPlayerEventCtrl.pendingState != APP_AUDIO_NONE))
    {
        trackNo = App_DfPlayer_GetEventTrackNo(ctx->dfPlayerEventCtrl.pendingState);

        if (trackNo != 0U)
        {
            (void)DFPlayer_PlayFolderTrack(
                DFPLAYER_CHANNEL_EVENT,
                P_DFPLAYER_EVENT_FOLDER_NO,
                trackNo);
        }

        ctx->dfPlayerEventCtrl.playReq = FALSE;
        ctx->dfPlayerEventCtrl.pendingState = APP_AUDIO_NONE;
    }
}
