/**********************************************************************************************************************
 * \file App_Buzzer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "App_Buzzer.h"
#include "ActEcu_Params.h"
#include "Driver_Buzzer.h"

void App_Buzzer_Init(App_Context *ctx)
{
    ctx->buzzerCtrl.buzzerOn = FALSE;
    ctx->buzzerCtrl.buzzerPrevOn = FALSE;
    ctx->buzzerCtrl.buzzerElapsedMs = 0U;
    ctx->buzzerCtrl.noteIdx = P_BUZZER_OFF_NOTE_IDX;
    ctx->buzzerCtrl.prevNoteIdx = P_BUZZER_OFF_NOTE_IDX;

    Driver_Buzzer_Off();
}

void App_Buzzer_Task(App_Context *ctx)
{
    uint16 onMs = 0U;
    uint16 offMs = 0U;
    uint8 targetNote = P_BUZZER_OFF_NOTE_IDX;

    switch (ctx->state.safeState)
    {
    case ACTECU_SAFE_CRITICAL:
        targetNote = P_BUZZER_CRITICAL_NOTE_IDX;
        onMs = P_BUZZER_CRITICAL_ON_MS;
        offMs = P_BUZZER_CRITICAL_OFF_MS;
        break;

    case ACTECU_SAFE_FATAL_NO_RESPONSE:
        targetNote = P_BUZZER_FATAL_NOTE_IDX;
        onMs = P_BUZZER_FATAL_ON_MS;
        offMs = P_BUZZER_FATAL_OFF_MS;
        break;

    case ACTECU_SAFE_NORMAL:
    case ACTECU_SAFE_WARNING:
    default:
        ctx->buzzerCtrl.buzzerOn = FALSE;
        ctx->buzzerCtrl.buzzerElapsedMs = 0U;
        ctx->buzzerCtrl.noteIdx = P_BUZZER_OFF_NOTE_IDX;
        return;
    }

    if (ctx->buzzerCtrl.noteIdx != targetNote)
    {
        ctx->buzzerCtrl.noteIdx = targetNote;
        ctx->buzzerCtrl.buzzerOn = TRUE;
        ctx->buzzerCtrl.buzzerElapsedMs = 0U;
        return;
    }

    ctx->buzzerCtrl.noteIdx = targetNote;
    ctx->buzzerCtrl.buzzerElapsedMs += ACTECU_BUZZER_TASK_PERIOD_MS;

    if (ctx->buzzerCtrl.buzzerOn == TRUE)
    {
        if (ctx->buzzerCtrl.buzzerElapsedMs >= onMs)
        {
            ctx->buzzerCtrl.buzzerOn = FALSE;
            ctx->buzzerCtrl.buzzerElapsedMs = 0U;
        }
    }
    else
    {
        if (ctx->buzzerCtrl.buzzerElapsedMs >= offMs)
        {
            ctx->buzzerCtrl.buzzerOn = TRUE;
            ctx->buzzerCtrl.buzzerElapsedMs = 0U;
        }
    }
}

void App_Buzzer_Apply(App_Context *ctx)
{
    if (ctx->buzzerCtrl.buzzerOn == TRUE)
    {
        if ((ctx->buzzerCtrl.buzzerPrevOn == FALSE) ||
            (ctx->buzzerCtrl.prevNoteIdx != ctx->buzzerCtrl.noteIdx))
        {
            Driver_Buzzer_SetNote(ctx->buzzerCtrl.noteIdx);
        }
    }
    else
    {
        if (ctx->buzzerCtrl.buzzerPrevOn == TRUE)
        {
            Driver_Buzzer_Off();
        }
    }

    ctx->buzzerCtrl.buzzerPrevOn = ctx->buzzerCtrl.buzzerOn;
    ctx->buzzerCtrl.prevNoteIdx = ctx->buzzerCtrl.noteIdx;
}
