/**********************************************************************************************************************
 * \file Driver_Servo.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Driver_Servo.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"
#include "IfxGtm.h"
#include "IfxStm.h"
#include "Bsp.h"
#include "ActEcu_Cfg.h"

static IfxGtm_Tom_Pwm_Config g_tom_config_servo1;
static IfxGtm_Tom_Pwm_Driver g_tom_driver_servo1;

static IfxGtm_Tom_Pwm_Config g_tom_config_servo2;
static IfxGtm_Tom_Pwm_Driver g_tom_driver_servo2;

static IfxGtm_Tom_Pwm_Config g_tom_config_servo3;
static IfxGtm_Tom_Pwm_Driver g_tom_driver_servo3;

static uint32 servo_pulse_us_to_ticks(uint32 pulse_us)
{
    return (uint32)(((uint64)ACTECU_SERVO_TOM_CLK_HZ * (uint64)pulse_us) / 1000000ULL);
}

static uint32 driver_servo_clamp_pulse_us(uint32 pulse_us)
{
    if (pulse_us < ACTECU_SERVO_MIN_US)
    {
        pulse_us = ACTECU_SERVO_MIN_US;
    }
    else if (pulse_us > ACTECU_SERVO_MAX_US)
    {
        pulse_us = ACTECU_SERVO_MAX_US;
    }

    return pulse_us;
}

static void driver_servo_init_channel(IfxGtm_Tom_Pwm_Config *config,
                                      IfxGtm_Tom_Pwm_Driver *driver,
                                      const IfxGtm_Tom_ToutMap *pin_map)
{
    IfxGtm_Tom_Pwm_initConfig(config, &MODULE_GTM);

    config->clock                    = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk1;
    config->tom                      = pin_map->tom;
    config->tomChannel               = pin_map->channel;
    config->pin.outputPin            = pin_map;
    config->period                   = ACTECU_SERVO_PERIOD_TICKS;
    config->dutyCycle                = servo_pulse_us_to_ticks(ACTECU_SERVO_CENTER_US);
    config->synchronousUpdateEnabled = TRUE;

    IfxGtm_Tom_Pwm_init(driver, config);
    IfxGtm_Tom_Pwm_start(driver, TRUE);
}

static void driver_servo_update_channel(IfxGtm_Tom_Pwm_Config *config,
                                        IfxGtm_Tom_Pwm_Driver *driver,
                                        uint32 pulse_us)
{
    config->dutyCycle = servo_pulse_us_to_ticks(pulse_us);
    IfxGtm_Tom_Pwm_init(driver, config);
}

void Driver_Servo_Init(void)
{
    IfxGtm_enable(&MODULE_GTM);
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);

    driver_servo_init_channel(&g_tom_config_servo1, &g_tom_driver_servo1, &ACTECU_SERVO1_PIN);
    driver_servo_init_channel(&g_tom_config_servo2, &g_tom_driver_servo2, &ACTECU_SERVO2_PIN);
    driver_servo_init_channel(&g_tom_config_servo3, &g_tom_driver_servo3, &ACTECU_SERVO3_PIN);
}

void setServo1PulseUs(uint32 pulse_us)
{
    pulse_us = driver_servo_clamp_pulse_us(pulse_us);
    driver_servo_update_channel(&g_tom_config_servo1, &g_tom_driver_servo1, pulse_us);
}

void setServo2PulseUs(uint32 pulse_us)
{
    pulse_us = driver_servo_clamp_pulse_us(pulse_us);
    driver_servo_update_channel(&g_tom_config_servo2, &g_tom_driver_servo2, pulse_us);
}

void setServo3PulseUs(uint32 pulse_us)
{
    pulse_us = driver_servo_clamp_pulse_us(pulse_us);
    driver_servo_update_channel(&g_tom_config_servo3, &g_tom_driver_servo3, pulse_us);
}

void setServoAllPulseUs(uint32 pulse_us)
{
    pulse_us = driver_servo_clamp_pulse_us(pulse_us);
    driver_servo_update_channel(&g_tom_config_servo1, &g_tom_driver_servo1, pulse_us);
    driver_servo_update_channel(&g_tom_config_servo2, &g_tom_driver_servo2, pulse_us);
    driver_servo_update_channel(&g_tom_config_servo3, &g_tom_driver_servo3, pulse_us);
}

/* 기존 코드 호환용 */
void setServoPulseUs(uint32 pulse_us)
{
    setServoAllPulseUs(pulse_us);
}

void servoRampUs(uint32 start_us, uint32 end_us, uint32 total_ms, uint32 step_ms)
{
    uint32 i;
    uint32 step_count;
    sint32 diff;

    if (step_ms == 0U)
    {
        step_ms = 20U;
    }

    step_count = total_ms / step_ms;
    if (step_count == 0U)
    {
        step_count = 1U;
    }

    diff = (sint32)end_us - (sint32)start_us;

    for (i = 0U; i <= step_count; i++)
    {
        uint32 pulse_us;

        pulse_us = (uint32)((sint32)start_us + ((diff * (sint32)i) / (sint32)step_count));
        setServoAllPulseUs(pulse_us);

        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, step_ms));
    }

    setServoAllPulseUs(end_us);
}