/**********************************************************************************************************************
 * \file Driver_Stm.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "Driver_Stm.h"
#include "IfxStm.h"
#include "IfxCpu_Irq.h"

typedef struct
{
    Ifx_STM              *stm_sfr;
    IfxStm_CompareConfig  stm_config;
    volatile uint32       counter;
} App_Stm;

static App_Stm g_stm;
static volatile uint32 g_counter_1ms = 0u;

volatile SchedulingFlag st_scheduling_info = {0u, 0u, 0u, 0u};
volatile stTestCnt st_test_cnt_info = {0u, 0u, 0u, 0u};

IFX_INTERRUPT(STM_Int0Handler, 0, 100);

void STM_Int0Handler(void)
{
    IfxCpu_enableInterrupts();

    IfxStm_clearCompareFlag(g_stm.stm_sfr, g_stm.stm_config.comparator);
    IfxStm_increaseCompare(g_stm.stm_sfr, g_stm.stm_config.comparator, 100000u);

    g_counter_1ms++;

    st_test_cnt_info.cnt_1ms++;

    if ((g_counter_1ms % 1u) == 0u)
    {
        st_scheduling_info.scheduling_1ms_flag = 1u;
    }

    if ((g_counter_1ms % 10u) == 0u)
    {
        st_scheduling_info.scheduling_10ms_flag = 1u;
        st_test_cnt_info.cnt_10ms++;
    }

    if ((g_counter_1ms % 100u) == 0u)
    {
        st_scheduling_info.scheduling_100ms_flag = 1u;
        st_test_cnt_info.cnt_100ms++;
    }

    if ((g_counter_1ms % 1000u) == 0u)
    {
        st_scheduling_info.scheduling_1000ms_flag = 1u;
        st_test_cnt_info.cnt_1000ms++;
    }
}

void Driver_Stm_Init(void)
{
    boolean interrupt_state = IfxCpu_disableInterrupts();

    g_counter_1ms = 0u;

    st_scheduling_info.scheduling_1ms_flag = 0u;
    st_scheduling_info.scheduling_10ms_flag = 0u;
    st_scheduling_info.scheduling_100ms_flag = 0u;
    st_scheduling_info.scheduling_1000ms_flag = 0u;

    st_test_cnt_info.cnt_1ms = 0u;
    st_test_cnt_info.cnt_10ms = 0u;
    st_test_cnt_info.cnt_100ms = 0u;
    st_test_cnt_info.cnt_1000ms = 0u;

    IfxStm_enableOcdsSuspend(&MODULE_STM0);

    g_stm.stm_sfr = &MODULE_STM0;
    IfxStm_initCompareConfig(&g_stm.stm_config);

    g_stm.stm_config.comparator      = IfxStm_Comparator_0;
    g_stm.stm_config.triggerPriority = 100u;
    g_stm.stm_config.typeOfService   = IfxSrc_Tos_cpu0;
    g_stm.stm_config.ticks           = 100000u;

    IfxStm_initCompare(g_stm.stm_sfr, &g_stm.stm_config);

    IfxCpu_restoreInterrupts(interrupt_state);
}
