/**********************************************************************************************************************
 * \file Driver_Buzzer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Driver_Buzzer.h"
#include "Ifx_Types.h"
#include "IfxGtm_Tom_Pwm.h"
#include "IfxGtm.h"

#define BUZZER_PIN              IfxGtm_TOM0_9_TOUT1_P02_1_OUT
#define BUZZER_TOM_CLK_HZ       6250000U

#define BUZZER_NOTE_IDX_C4      0U
#define BUZZER_NOTE_IDX_OFF     14U

static IfxGtm_Tom_Pwm_Config  g_buzzerTomConfig;
static IfxGtm_Tom_Pwm_Driver  g_buzzerTomDriver;


void Driver_Buzzer_Off(void);

void Driver_Buzzer_Init(void)
{
    IfxGtm_enable(&MODULE_GTM);
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);

    IfxGtm_Tom_Pwm_initConfig(&g_buzzerTomConfig, &MODULE_GTM);

    g_buzzerTomConfig.tom                      = BUZZER_PIN.tom;
    g_buzzerTomConfig.tomChannel               = BUZZER_PIN.channel;
    g_buzzerTomConfig.pin.outputPin            = &BUZZER_PIN;
    g_buzzerTomConfig.clock                    = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk1;
    g_buzzerTomConfig.period                   = 1000U;
    g_buzzerTomConfig.dutyCycle                = 0U;
    g_buzzerTomConfig.synchronousUpdateEnabled = TRUE;

    IfxGtm_Tom_Pwm_init(&g_buzzerTomDriver, &g_buzzerTomConfig);
    IfxGtm_Tom_Pwm_start(&g_buzzerTomDriver, TRUE);

    Driver_Buzzer_Off();
}

void makeSound(unsigned int sound)
{
    unsigned int uPeriod = 0U;
    float fBuzz[15] =
    {
        261.63f,   /* 0: 도 (C4) */
        277.18f,
        293.66f,
        311.13f,
        329.63f,
        349.23f,
        369.99f,
        392.00f,
        415.30f,
        440.00f,
        466.16f,
        493.88f,
        523.25f,
        554.37f,
        0.0f       /* 14: 무음 */
    };

    if (sound >= 15U)
    {
        sound = 14U;
    }

    if (sound == 14U)
    {
        g_buzzerTomConfig.dutyCycle = 0U;
        IfxGtm_Tom_Pwm_init(&g_buzzerTomDriver, &g_buzzerTomConfig);
        return;
    }

    uPeriod = (unsigned int)(6250000.0f / fBuzz[sound]);

    g_buzzerTomConfig.period = uPeriod;
    g_buzzerTomConfig.dutyCycle = (unsigned int)(uPeriod * 0.3f);

    IfxGtm_Tom_Pwm_init(&g_buzzerTomDriver, &g_buzzerTomConfig);
}

void Driver_Buzzer_On(void)
{
    makeSound(BUZZER_NOTE_IDX_C4);
}

void Driver_Buzzer_Off(void)
{
    makeSound(BUZZER_NOTE_IDX_OFF);
}

