/**********************************************************************************************************************
 * \file App_Scheduler.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "App_Scheduler.h"

#include "App_Led.h"
#include "App_Buzzer.h"
#include "App_Servo.h"
#include "App_DfPlayer.h"

#include "Driver_Stm.h"
#include "Ifx_Types.h"

static App_Context g_app_ctx;

static void app_scheduler_task_1ms(void);
static void app_scheduler_task_10ms(void);
static void app_scheduler_task_100ms(void);
static void app_scheduler_task_1000ms(void);

void App_Scheduler_SetSafeState(ActEcu_SafeState state)
{
    switch (state)
    {
    case ACTECU_SAFE_NORMAL:
    case ACTECU_SAFE_WARNING:
    case ACTECU_SAFE_CRITICAL:
    case ACTECU_SAFE_FATAL_NO_RESPONSE:
        g_app_ctx.state.safe_state = state;
        break;

    default:
        g_app_ctx.state.safe_state = ACTECU_SAFE_NORMAL;
        break;
    }
}

void App_Scheduler_SetSpeedState(uint8 speed_state)
{
    g_app_ctx.input.speed_state_raw = speed_state;
}

void App_Scheduler_SetBrakeActive(uint8 brake_active)
{
    g_app_ctx.input.brake_active = (brake_active != 0U) ? 1U : 0U;
}

void App_Scheduler_SetEventState(uint8 ev_state)
{
    g_app_ctx.input.ev_state = ev_state;
}

void App_Scheduler_SetAckButton(uint8 ack_button)
{
    g_app_ctx.input.ack_button = (ack_button != 0U) ? 1U : 0U;
}

void App_Scheduler_Init(void)
{
    g_app_ctx.input.safe_state_raw  = 0U;
    g_app_ctx.input.speed_state_raw = 0U;
    g_app_ctx.input.brake_active    = 0U;
    g_app_ctx.input.ev_state        = 0U;
    g_app_ctx.input.ack_button      = 0U;
    g_app_ctx.input.msg_valid       = 0U;
    g_app_ctx.input.alive_cnt       = 0U;
    g_app_ctx.input.ack_seq         = 0U;
    g_app_ctx.input.ack_seq_prev    = 0U;

    App_Scheduler_SetSafeState(ACTECU_SAFE_NORMAL);

    App_Led_Init(&g_app_ctx);
    App_Buzzer_Init(&g_app_ctx);
    App_Servo_Init(&g_app_ctx);
    App_DfPlayer_Init(&g_app_ctx);
}

void App_Scheduler_Run(void)
{
    if (st_scheduling_info.scheduling_1ms_flag == 1u)
    {
        st_scheduling_info.scheduling_1ms_flag = 0u;
        app_scheduler_task_1ms();

        if (st_scheduling_info.scheduling_10ms_flag == 1u)
        {
            st_scheduling_info.scheduling_10ms_flag = 0u;
            app_scheduler_task_10ms();
        }

        if (st_scheduling_info.scheduling_100ms_flag == 1u)
        {
            st_scheduling_info.scheduling_100ms_flag = 0u;
            app_scheduler_task_100ms();
        }

        if (st_scheduling_info.scheduling_1000ms_flag == 1u)
        {
            st_scheduling_info.scheduling_1000ms_flag = 0u;
            app_scheduler_task_1000ms();
        }
    }
}

static void app_scheduler_task_1ms(void)
{
    /* empty */
}

static void app_scheduler_task_10ms(void)
{
    App_Led1_Task(&g_app_ctx);
    App_Led1_Apply(&g_app_ctx);

    App_Led2_Task(&g_app_ctx);
    App_Led2_Apply(&g_app_ctx);

    App_Led3_Task(&g_app_ctx);
    App_Led3_Apply(&g_app_ctx);

    App_Buzzer_Task(&g_app_ctx);
    App_Buzzer_Apply(&g_app_ctx);

    App_Servo_Task(&g_app_ctx);

    App_DfPlayer_Task(&g_app_ctx);
    App_DfPlayer_Apply(&g_app_ctx);
}

static void app_scheduler_task_100ms(void)
{
    /* empty */
}

static void app_scheduler_task_1000ms(void)
{
    /* empty */
}