/**********************************************************************************************************************
 * \file App_Schedular.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "App_Scheduler.h"
#include "Driver_DfPlayer.h"
#include "Driver_Stm.h"
#include "Driver_Led.h"
#include "Driver_Buzzer.h"
#include "Driver_Can.h"
#include "Ifx_Types.h"
#include "ActEcu_Cfg.h"

static boolean g_ledOn = FALSE;
static boolean g_buzzerOn = FALSE;

static boolean g_audioPlayReq = FALSE;
static boolean g_audioReleasePending = FALSE;
static uint16  g_audioReleaseMs = 0U;

void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

static void requestOneShotOutputs(void)
{
    g_audioPlayReq = TRUE;
}

void App_Scheduler_Init(void)
{
    g_ledOn = FALSE;
    g_buzzerOn = FALSE;
}

void App_Scheduler_Run(void)
{
    if (stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if (stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if (stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }

        if (stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}

void AppTask1ms(void)
{

}
void AppTask10ms(void)
{
    if (g_oneShotActive == 1u)
    {
        requestOneShotOutputs();
        Driver_Led_On_2();   // 예: LED12 ON
        g_oneShotCnt++;

        if (g_oneShotCnt >= ACTECU_ONE_SHOT_HOLD_COUNT)   // 20 * 10ms = 200ms
        {
            Driver_Led_Off_2(); // OFF
            g_oneShotActive = 0u;
            g_oneShotCnt = 0u;
        }
    }
    else
    {
        Driver_Led_Off_2();
    }
//    if (g_servoActive == TRUE)
//    {
//        uint32 pulseUs;
//
//        g_servoElapsedMs += SERVO_TASK_STEP_MS;
//        if (g_servoElapsedMs >= SERVO_TOTAL_MS)
//        {
//            g_servoElapsedMs = SERVO_TOTAL_MS;
//            g_servoActive = FALSE;
//        }
//
//        pulseUs = SERVO_START_US
//                + (((SERVO_END_US - SERVO_START_US) * g_servoElapsedMs) / SERVO_TOTAL_MS);
//
//        setServoPulseUs(pulseUs);
//    }
//
    if (g_audioPlayReq == TRUE)
    {
        g_audioPlayReq = FALSE;

        /* 트랙 1회 재생 */
        (void)DFPlayer_sendCmdOnce(0x0F, ACTECU_DFPLAYER_TRACK_NUM);

        g_audioReleasePending = TRUE;
        g_audioReleaseMs = ACTECU_DFPLAYER_TX_RELEASE_MS;
    }
}
void AppTask100ms(void)
{
    /* LED 100ms 토글 */
    g_ledOn = !g_ledOn;
    if (g_ledOn == TRUE)
    {
        Driver_Led_On_1();
    }
    else
    {
        Driver_Led_Off_1();
    }

    /* 부저 100ms 토글 */
    g_buzzerOn = !g_buzzerOn;
    if (g_buzzerOn == TRUE)
    {
        Driver_Buzzer_On();
    }
    else
    {
        Driver_Buzzer_Off();
    }
}
void AppTask1000ms(void)
{

}



