/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"
#include "Bsp.h"

#include "Driver_Stm.h"
//#include "Driver_Can.h"
#include "Driver_Led.h"
#include "Driver_Buzzer.h"
#include "Driver_Servo.h"
#include "Driver_DfPlayer.h"

#include "App_Scheduler.h"
#include "ActEcu_Params.h"
#include "Virtual_Input.h"

IfxCpu_syncEvent cpuSyncEvent = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();

    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    Driver_Led_Init();
    Driver_Buzzer_Init();
    Driver_Servo_Init();
    Driver_DfPlayer_Init();
//    Driver_Can_Init();

    Virtual_Input_Init();

    App_Scheduler_Init();
    Driver_Buzzer_Off();

    /* 상태 스피커 초기 설정 */
    (void)DFPlayer_SendCmd(DFPLAYER_CHANNEL_STATE, 0x06U, 20U);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 100));
    (void)DFPlayer_SendCmd(DFPLAYER_CHANNEL_STATE, 0x09U, 0x0002U);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 100));

    /* 이벤트 스피커 초기 설정 */
    (void)DFPlayer_SendCmd(DFPLAYER_CHANNEL_EVENT, 0x06U, 30U);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 100));
    (void)DFPlayer_SendCmd(DFPLAYER_CHANNEL_EVENT, 0x09U, 0x0002U);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 100));

    Driver_Stm_Init();

    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    while (1)
    {
//        Driver_Can_Task();
        Virtual_Input_Task();
        App_Scheduler_Run();
    }

    return 0;
}
