/**********************************************************************************************************************
 * \file ActEcu_Cfg.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ACTECU_CFG_H_
#define ACTECU_CFG_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* LED1 */
#define ACTECU_LED1_PIN                        IfxPort_P02_6

/* LED2 group (brake lamp) */
#define ACTECU_LED2_1_PIN                      IfxPort_P10_1
#define ACTECU_LED2_2_PIN                      IfxPort_P10_3
#define ACTECU_LED2_3_PIN                      IfxPort_P10_5
#define ACTECU_LED2_4_PIN                      IfxPort_P02_7

/* LED3 group (door lock) */
#define ACTECU_LED3_NORMAL_PIN                 IfxPort_P02_0
#define ACTECU_LED3_FATAL_PIN                  IfxPort_P02_1

/* Buzzer hardware */
#define ACTECU_BUZZER_PIN                      IfxGtm_TOM1_13_TOUT5_P02_5_OUT
#define ACTECU_BUZZER_TOM_CLK_HZ               6250000U

/* Servo hardware */
#define ACTECU_SERVO_TOM_CLK_HZ                6250000U
#define ACTECU_SERVO1_PIN                      IfxGtm_TOM0_11_TOUT3_P02_3_OUT
#define ACTECU_SERVO2_PIN                      IfxGtm_TOM0_12_TOUT4_P02_4_OUT
#define ACTECU_SERVO3_PIN                      IfxGtm_TOM0_2_TOUT104_P10_2_OUT
#define ACTECU_SERVO_PERIOD_TICKS              125000U

#define ACTECU_SERVO_MIN_US                    1000U
#define ACTECU_SERVO_CENTER_US                 1500U
#define ACTECU_SERVO_MAX_US                    2000U

/* ------------------------------------------------------------------ */
/* DFPlayer #1 : State speaker (P33.9 / ASCLIN2 TX)                   */
/* ------------------------------------------------------------------ */
#define ACTECU_DFPLAYER_STATE_ASCLIN           MODULE_ASCLIN2
#define ACTECU_DFPLAYER_STATE_BAUDRATE         9600U
#define ACTECU_DFPLAYER_STATE_TX_PIN           IfxAsclin2_TX_P33_9_OUT
#define ACTECU_DFPLAYER_STATE_ISR_TX_PRIORITY  18U

#define ACTECU_DFPLAYER_STATE_TX_RELEASE_PORT  (&MODULE_P33)
#define ACTECU_DFPLAYER_STATE_TX_RELEASE_PIN   9U

/* ------------------------------------------------------------------ */
/* DFPlayer #2 : Event speaker (P20.0 / ASCLIN3 TX)                   */
/* ------------------------------------------------------------------ */
#define ACTECU_DFPLAYER_EVENT_ASCLIN           MODULE_ASCLIN3
#define ACTECU_DFPLAYER_EVENT_BAUDRATE         9600U
#define ACTECU_DFPLAYER_EVENT_TX_PIN           IfxAsclin3_TX_P20_0_OUT
#define ACTECU_DFPLAYER_EVENT_ISR_TX_PRIORITY  19U

#define ACTECU_DFPLAYER_EVENT_TX_RELEASE_PORT  (&MODULE_P20)
#define ACTECU_DFPLAYER_EVENT_TX_RELEASE_PIN   0U
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/


#endif /* ACTECU_CFG_H_ */
