/**********************************************************************************************************************
 * \file App_Servo.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "App_Servo.h"

#include "ActEcu_Params.h"
#include "Driver_Servo.h"

static void App_Servo_MoveAllToStart(const App_Context *ctx)
{
    setServo1PulseUs(ctx->servo1Ctrl.startPulseUs);
    setServo2PulseUs(ctx->servo2Ctrl.startPulseUs);
}

static void App_Servo_MoveServo1ToTarget(const App_Context *ctx)
{
    setServo1PulseUs(ctx->servo1Ctrl.targetPulseUs);
}

static void App_Servo_MoveServo2ToTarget(const App_Context *ctx)
{
    setServo2PulseUs(ctx->servo2Ctrl.targetPulseUs);
}

void App_Servo_Init(App_Context *ctx)
{
    ctx->servo1Ctrl.startPulseUs = P_SERVO1_START_US;
    ctx->servo1Ctrl.targetPulseUs = P_SERVO1_TARGET_US;

    ctx->servo2Ctrl.startPulseUs = P_SERVO2_START_US;
    ctx->servo2Ctrl.targetPulseUs = P_SERVO2_TARGET_US;

    ctx->prevSafeState = ctx->state.safeState;

    App_Servo_MoveAllToStart(ctx);
}

void App_Servo_Task(App_Context *ctx)
{
    ActEcu_SafeState prevState = ctx->prevSafeState;
    ActEcu_SafeState currState = ctx->state.safeState;

    if (prevState == currState)
    {
        return;
    }

    if ((prevState != ACTECU_SAFE_NORMAL) &&
        (currState == ACTECU_SAFE_NORMAL))
    {
        App_Servo_MoveAllToStart(ctx);
    }

    if ((prevState != ACTECU_SAFE_CRITICAL) &&
        (currState == ACTECU_SAFE_CRITICAL))
    {
        App_Servo_MoveServo1ToTarget(ctx);
    }

    if ((prevState != ACTECU_SAFE_FATAL_NO_RESPONSE) &&
        (currState == ACTECU_SAFE_FATAL_NO_RESPONSE))
    {
        App_Servo_MoveServo2ToTarget(ctx);
    }

    ctx->prevSafeState = currState;
}
