/**********************************************************************************************************************
 * \file App_Servo.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "App_Servo.h"

#include "ActEcu_Params.h"
#include "Driver_Servo.h"

void App_Servo_Init(App_Context *ctx)
{
    ctx->servoCtrl.startReq      = FALSE;
    ctx->servoCtrl.active        = FALSE;
    ctx->servoCtrl.elapsedMs     = 0U;
    ctx->servoCtrl.startPulseUs  = P_SERVO_START_US;
    ctx->servoCtrl.targetPulseUs = P_SERVO_TARGET_US;

    setServoPulseUs(P_SERVO_START_US);
}

void App_Servo_RequestOneShot(App_Context *ctx)
{
    if (ctx->servoCtrl.active == FALSE)
    {
        ctx->servoCtrl.startReq = TRUE;
    }
}

void App_Servo_Task(App_Context *ctx)
{
    sint32 diff;
    uint32 pulseUs;

    if (ctx->servoCtrl.startReq == TRUE)
    {
        ctx->servoCtrl.startReq = FALSE;
        ctx->servoCtrl.active = TRUE;
        ctx->servoCtrl.elapsedMs = 0U;

        setServoPulseUs(ctx->servoCtrl.startPulseUs);
        return;
    }

    if (ctx->servoCtrl.active == FALSE)
    {
        return;
    }

    ctx->servoCtrl.elapsedMs += ACTECU_SERVO_TASK_PERIOD_MS;

    if (ctx->servoCtrl.elapsedMs >= P_SERVO_RUN_MS)
    {
        ctx->servoCtrl.elapsedMs = P_SERVO_RUN_MS;
        setServoPulseUs(ctx->servoCtrl.targetPulseUs);
        ctx->servoCtrl.active = FALSE;
        return;
    }

    diff = (sint32)ctx->servoCtrl.targetPulseUs - (sint32)ctx->servoCtrl.startPulseUs;

    pulseUs = (uint32)((sint32)ctx->servoCtrl.startPulseUs
            + ((diff * (sint32)ctx->servoCtrl.elapsedMs) / (sint32)P_SERVO_RUN_MS));

    setServoPulseUs(pulseUs);
}
