/**********************************************************************************************************************
 * \file Virtual_Input.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/**********************************************************************************************************************
 * \file Virtual_Input.c
 *********************************************************************************************************************/

#include "Virtual_Input.h"
#include "Driver_Can.h"
#include "App_Scheduler.h"
#include "ActEcu_Types.h"

volatile VirtualInput_Shared g_virtualInputShared = {0u, 0u, {0u, 0u, 0u}, 0u};

/*
 * App_Scheduler.c가 그대로 쓰고 있는 전역 심볼을 여기서 정의한다.
 * 따라서 이번 테스트 단계에서는 Driver_Can.c를 빌드에서 제외해야 한다.
 */
volatile uint8  g_oneShotActive = 0u;
volatile uint16 g_oneShotCnt    = 0u;

static uint32 g_lastSeqCpu0 = 0u;
static uint8  g_prevAckSeqCpu0 = 0u;
static uint8  g_ackSeqInitialized = 0u;

static App_InputSignals g_rxSignals;

static ActEcu_SafeState decodeSafeState(uint8 rawSafeState)
{
    switch (rawSafeState)
    {
    case ACTECU_SAFE_NORMAL:
        return ACTECU_SAFE_NORMAL;
    case ACTECU_SAFE_WARNING:
        return ACTECU_SAFE_WARNING;
    case ACTECU_SAFE_CRITICAL:
        return ACTECU_SAFE_CRITICAL;
    case ACTECU_SAFE_FATAL_NO_RESPONSE:
        return ACTECU_SAFE_FATAL_NO_RESPONSE;
    default:
        return ACTECU_SAFE_NORMAL;
    }
}

void Virtual_Input_Init(void)
{
    g_virtualInputShared.valid = 0u;
    g_virtualInputShared.seq = 0u;
    g_virtualInputShared.data[0] = 0u;
    g_virtualInputShared.data[1] = 0u;
    g_virtualInputShared.data[2] = 0u;
    g_virtualInputShared.reserved = 0u;

    g_lastSeqCpu0 = 0u;
    g_prevAckSeqCpu0 = 0u;
    g_ackSeqInitialized = 0u;

    g_rxSignals.safeStateRaw = 0u;
    g_rxSignals.speedStateRaw = 0u;
    g_rxSignals.brakeActive = 0u;
    g_rxSignals.evState = 0u;
    g_rxSignals.ackButton = 0u;
    g_rxSignals.msgValid = 0u;
    g_rxSignals.aliveCnt = 0u;
    g_rxSignals.ackSeq = 0u;
    g_rxSignals.ackSeqPrev = 0u;

    g_oneShotActive = 0u;
    g_oneShotCnt = 0u;
}

void Virtual_Input_Task(void)
{
    uint32 currSeq;
    uint8  byte0;
    uint8  byte1;
    uint8  byte2;
    uint8  rawSafeState;
    uint8  rawSpeedState;
    uint8  brakeActive;
    uint8  evState;
    uint8  ackButton;
    uint8  msgValid;
    uint8  aliveCnt;
    uint8  ackSeq;

    if (g_virtualInputShared.valid == 0u)
    {
        return;
    }

    currSeq = g_virtualInputShared.seq;

    if (currSeq == g_lastSeqCpu0)
    {
        return;
    }

    byte0 = g_virtualInputShared.data[0];
    byte1 = g_virtualInputShared.data[1];
    byte2 = g_virtualInputShared.data[2];

    rawSafeState = (uint8)(byte0 & 0x0Fu);
    rawSpeedState = (uint8)((byte0 >> 4) & 0x0Fu);

    brakeActive = (uint8)(byte1 & 0x01u);
    evState = (uint8)((byte1 >> 1) & 0x0Fu);
    ackButton = (uint8)((byte1 >> 5) & 0x01u);
    msgValid = (uint8)((byte1 >> 6) & 0x01u);

    aliveCnt = (uint8)(byte2 & 0x0Fu);
    ackSeq = (uint8)((byte2 >> 4) & 0x0Fu);

    g_rxSignals.safeStateRaw = rawSafeState;
    g_rxSignals.speedStateRaw = rawSpeedState;
    g_rxSignals.brakeActive = brakeActive;
    g_rxSignals.evState = evState;
    g_rxSignals.ackButton = ackButton;
    g_rxSignals.msgValid = msgValid;
    g_rxSignals.aliveCnt = aliveCnt;
    g_rxSignals.ackSeqPrev = g_rxSignals.ackSeq;
    g_rxSignals.ackSeq = ackSeq;

    if (msgValid != 0u)
    {
        App_Scheduler_SetSafeState(decodeSafeState(rawSafeState));
        App_Scheduler_SetBrakeActive(brakeActive);

        if (g_ackSeqInitialized == 0u)
        {
            g_prevAckSeqCpu0 = ackSeq;
            g_ackSeqInitialized = 1u;
        }
        else
        {
            if ((ackButton != 0u) && (ackSeq != g_prevAckSeqCpu0))
            {
                g_oneShotActive = 1u;
                g_oneShotCnt = 0u;
            }

            g_prevAckSeqCpu0 = ackSeq;
        }
    }

    g_lastSeqCpu0 = currSeq;
}

void Virtual_Input_InjectorInit(void)
{
    g_virtualInputShared.valid = 0u;
    g_virtualInputShared.seq = 0u;
    g_virtualInputShared.data[0] = 0u;
    g_virtualInputShared.data[1] = 0u;
    g_virtualInputShared.data[2] = 0u;
    g_virtualInputShared.reserved = 0u;

    Virtual_Input_InjectorWriteFrame(0x00u, 0x40u, 0x00u);
}

void Virtual_Input_InjectorWriteFrame(uint8 byte0, uint8 byte1, uint8 byte2)
{
    g_virtualInputShared.valid = 0u;

    g_virtualInputShared.data[0] = byte0;
    g_virtualInputShared.data[1] = byte1;
    g_virtualInputShared.data[2] = byte2;
    g_virtualInputShared.reserved = 0u;

    g_virtualInputShared.seq++;
    g_virtualInputShared.valid = 1u;
}
