/**********************************************************************************************************************
 * \file ActEcu_Params.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ACTECU_PARAMS_H_
#define ACTECU_PARAMS_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ACTECU_LED1_TASK_PERIOD_MS              10U

#define P_LED1_CRITICAL_BLINK_ON_MS             500U
#define P_LED1_CRITICAL_BLINK_OFF_MS            500U

#define P_LED1_FATAL_BLINK_ON_MS                200U
#define P_LED1_FATAL_BLINK_OFF_MS               200U

#define ACTECU_BUZZER_TASK_PERIOD_MS            10U

#define P_BUZZER_CRITICAL_NOTE_IDX              0U
#define P_BUZZER_FATAL_NOTE_IDX                 12U
#define P_BUZZER_OFF_NOTE_IDX                   14U

#define P_BUZZER_CRITICAL_ON_MS                 500U
#define P_BUZZER_CRITICAL_OFF_MS                500U

#define P_BUZZER_FATAL_ON_MS                    150U
#define P_BUZZER_FATAL_OFF_MS                   150U

/* DFPlayer */
#define ACTECU_DFPLAYER_TASK_PERIOD_MS          10U
#define P_DFPLAYER_FOLDER_NO                    0x01U

#define P_DFPLAYER_TRACK_STARTUP                0x01U
#define P_DFPLAYER_TRACK_LOW_SPEED              0x02U
#define P_DFPLAYER_TRACK_MID_SPEED              0x03U
#define P_DFPLAYER_TRACK_HIGH_SPEED             0x04U
#define P_DFPLAYER_TRACK_RAPID_BRAKE            0x05U
#define P_DFPLAYER_TRACK_RAPID_ACCEL            0x06U
#define P_DFPLAYER_TRACK_STEER_LEVEL1           0x07U
#define P_DFPLAYER_TRACK_STEER_LEVEL2           0x08U
#define P_DFPLAYER_TRACK_FAULT                  0x09U
#define P_DFPLAYER_TRACK_FATAL                  0x0AU

#define P_DFPLAYER_EVENT_HOLD_MS                1500U

#define ACTECU_SERVO_TASK_PERIOD_MS             10U
#define P_SERVO_START_US                        1000U
#define P_SERVO_TARGET_US                       2000U
#define P_SERVO_RUN_MS                          1000U
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/


#endif /* ACTECU_PARAMS_H_ */
