/**********************************************************************************************************************
 * \file ActEcu_Cfg.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ACTECU_CFG_H_
#define ACTECU_CFG_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* LED */
#define ACTECU_LED_PIN                 IfxPort_P10_3
#define ACTECU_ONE_SHOT_LED_PIN        IfxPort_P10_1

/* Buzzer */
#define ACTECU_BUZZER_NOTE_IDX         0U
#define ACTECU_BUZZER_OFF_IDX          14U
#define ACTECU_BUZZER_PIN              IfxGtm_TOM0_9_TOUT1_P02_1_OUT
#define ACTECU_BUZZER_TOM_CLK_HZ       6250000U

/* Servo */
#define ACTECU_SERVO_TOM_CLK_HZ        6250000U
#define ACTECU_SERVO_PIN               IfxGtm_TOM0_11_TOUT3_P02_3_OUT
#define ACTECU_SERVO_PERIOD_TICKS      125000U

#define ACTECU_SERVO_MIN_US            1000U
#define ACTECU_SERVO_CENTER_US         1500U
#define ACTECU_SERVO_MAX_US            2000U

#define ACTECU_SERVO_START_US          1000U
#define ACTECU_SERVO_END_US            2000U
#define ACTECU_SERVO_TOTAL_MS          1000U
#define ACTECU_SERVO_TASK_STEP_MS      10U

/* DFPlayer */
#define ACTECU_DFPLAYER_TRACK_NUM      0x0103U
#define ACTECU_DFPLAYER_TX_RELEASE_MS  20U

/* One-shot */
#define ACTECU_ONE_SHOT_HOLD_COUNT     20U
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/


#endif /* ACTECU_CFG_H_ */