/**********************************************************************************************************************
 * \file ActEcu_Types.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ACTECU_TYPES_H_
#define ACTECU_TYPES_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "ActEcu_Enum.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
    uint8 safe_state_raw;
    uint8 speed_state_raw;
    uint8 brake_active;
    uint8 ev_state;
    uint8 ack_button;
    uint8 msg_valid;
    uint8 alive_cnt;
    uint8 ack_seq;
    uint8 ack_seq_prev;
} App_InputSignals;

typedef struct
{
    ActEcu_SafeState safe_state;
} App_State;

typedef struct
{
    boolean led1_on;
    uint16  led1_blink_elapsed_ms;
} App_Led1Control;

typedef struct
{
    uint8 brake_lamp_count;
} App_Led2Control;

typedef struct
{
    boolean normal_lamp_on;
    boolean fatal_lamp_on;
} App_Led3Control;

typedef struct
{
    boolean buzzer_on;
    boolean buzzer_prev_on;
    uint16  buzzer_elapsed_ms;
    uint8   note_idx;
    uint8   prev_note_idx;
} App_BuzzerControl;

typedef struct
{
    uint32 start_pulse_us;
    uint32 target_pulse_us;
} App_ServoControl;

typedef struct
{
    App_AudioState current_state;
    App_AudioState prev_applied_state;
    uint16         repeat_elapsed_ms;
} App_DfPlayerStateControl;

typedef struct
{
    App_AudioState pending_state;
    uint8          prev_ev_state;
    boolean        play_req;
} App_DfPlayerEventControl;

typedef struct
{
    App_InputSignals         input;
    App_State                state;
    App_Led1Control          led1_ctrl;
    App_Led2Control          led2_ctrl;
    App_Led3Control          led3_ctrl;
    App_BuzzerControl        buzzer_ctrl;

    App_ServoControl         servo1_ctrl;
    App_ServoControl         servo2_ctrl;
    App_ServoControl         servo3_ctrl;
    ActEcu_SafeState         prev_safe_state;

    App_DfPlayerStateControl df_player_state_ctrl;
    App_DfPlayerEventControl df_player_event_ctrl;
} App_Context;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

#endif /* ACTECU_TYPES_H_ */
