/**********************************************************************************************************************
 * \file ActEcu_Types.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ACTECU_TYPES_H_
#define ACTECU_TYPES_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "ActEcu_Enum.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "ActEcu_Enum.h"

typedef struct
{
    uint8 safeStateRaw;
    uint8 speedStateRaw;
    uint8 brakeActive;
    uint8 evState;
    uint8 ackButton;
    uint8 msgValid;
    uint8 aliveCnt;
    uint8 ackSeq;
    uint8 ackSeqPrev;
} App_InputSignals;

typedef struct
{
    ActEcu_SafeState safeState;
} App_State;

typedef struct
{
    boolean led1On;
    uint16  led1BlinkElapsedMs;
} App_Led1Control;

typedef struct
{
    uint8 brakeLampCount;
} App_Led2Control;

typedef struct
{
    boolean normalLampOn;
    boolean fatalLampOn;
} App_Led3Control;

typedef struct
{
    boolean buzzerOn;
    boolean buzzerPrevOn;
    uint16  buzzerElapsedMs;
    uint8   noteIdx;
    uint8   prevNoteIdx;
} App_BuzzerControl;

/* 네가 적용한 2서보 구조 유지 */
typedef struct
{
    uint32 startPulseUs;
    uint32 targetPulseUs;
} App_ServoControl;

/* 상태 스피커 제어용 */
typedef struct
{
    App_AudioState currentState;
    App_AudioState prevAppliedState;
    uint16         repeatElapsedMs;
} App_DfPlayerStateControl;

/* 이벤트 스피커 제어용 */
typedef struct
{
    App_AudioState pendingState;
    uint8          prevEvState;
    boolean        playReq;
} App_DfPlayerEventControl;

typedef struct
{
    App_InputSignals         input;
    App_State                state;
    App_Led1Control          led1Ctrl;
    App_Led2Control          led2Ctrl;
    App_Led3Control          led3Ctrl;
    App_BuzzerControl        buzzerCtrl;

    App_ServoControl         servo1Ctrl;
    App_ServoControl         servo2Ctrl;
    ActEcu_SafeState         prevSafeState;

    App_DfPlayerStateControl dfPlayerStateCtrl;
    App_DfPlayerEventControl dfPlayerEventCtrl;
} App_Context;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

#endif /* ACTECU_TYPES_H_ */
